### ISSUE TITLE
Collision functions

### ISSUE THREAD

**Issue by nobbele** [ggez/ggez#1009]
It's such a common thing to use in most types of games that I feel like we should maybe add some basic functions to check at least circle and rect intersections?

**Comment by PSteinhaus** [comment]
There are [`Rect::overlaps`](https://docs.rs/ggez/latest/ggez/graphics/struct.Rect.html#method.overlaps) and [`Rect::contains`](https://docs.rs/ggez/latest/ggez/graphics/struct.Rect.html#method.contains). To implement circle-rect collision checks we could add `Rect::overlaps_circle(center, radius)`. I'm not really convinced that we need it though, since we don't need it ourselves and it can be easily implemented by anyone who'd ever need it when needed.

**Comment by nobbele** [comment]
I like the overlaps_circle method idea. While it isn't that hard to implement, you gotta deal with both some math and abs(or min/max), pows and sqrts in a rusty manner. In my experience helping others, it's not an easy function to write yourself as a beginner. It's essential to two of the most basic games you can make (pong and breakout) so I think it's worth adding.

**Comment by PSteinhaus** [comment]
I see your point. It's probably really worth adding.

**Comment by nobbele** [comment]
Added in b436891
