### ISSUE TITLE
WGPU transition

### ISSUE THREAD

**Issue by LechintanTudor** [ggez/ggez#1012]
I have some free time in the following weeks, I could help with transitioning to WGPU if nobody is working on it at the moment.

**Comment by PSteinhaus** [comment]
Thank you! That's good to hear. @nobbele [startet to work on it](https://github.com/nobbele/ggez/tree/oblivion), some time ago, but we haven't yet found the time and energy to complete it since then. Feel free to take a look!

For me it will be a few weeks until I'll be able to really pull my weight in this again, but if you're interested and come across anything you'd like a quick explanation or second opinion on feel free to open an issue (probably on the [repo of the renderer behind the effort](https://github.com/nobbele/Oblivion)), or to just hit me up on Discord (where we can probably best be found over the Rust Game-Dev server).

**Comment by nobbele** [comment]
Oblivion currently has some major issues (Text / Mesh blinking). 

And I think that the API of the WGPU library should be the graphics module rather than ggez::graphics being wrappers for graphics types like Oblivion is currently integrated. For this to work while being framework-agnostic all the functions have to take a generic context, my ideas for this is to either take `&mut impl HasContext`, or add a type parameter `struct Text<T: HasContext>` and re-export `pub type Text = wgpu_library::Text<Context>`.

Also due to the lack of lifetimes and mixed retained/immediate-mode drawing, there's no simple way to get wgpu to render your objects. Oblivion uses a queue system with Arcs but other ideas could be to use arenas.

**Comment by LechintanTudor** [comment]
Thanks for the replies! For now, I'll try to port the existing code to WGPU with as few changes as possible and see if it works out.

**Comment by nobbele** [comment]
Good luck!

**Comment by aleokdev** [comment]
@jazzfool over at the [wgpu branch on my fork](https://github.com/aleokdev/ggez/tree/wgpu) has practically finished with the interface and is now squashing the few bugs that are remaining. One thing to note is that we are changing the interface drastically, taking a data-driven approach. The entire interface will change, and it'll result in a completely different (but still simple and easy to use) crate.

**Comment by nobbele** [comment]
@aleokdev I just saw your implementation, it looks very good!
Could you make Canvas and Text only contain owning types though? Using lifetimes (in public API) is against the ggez way of doing things.

**Comment by aleokdev** [comment]
> Using lifetimes (in public API) is against the ggez way of doing things.

IMO, you should reconsider this "way of doing things". Although it is true that lifetimes do create complex compiling issues if misused, they also do their work flawlessly in avoiding memory safety issues without misusing reference counters everywhere. They're one of the most misunderstood features of the language, and although I can understand this from a beginner's standpoint, it ends up being wasted potential for the rest of the userbase. As such, I recommend that, instead of avoiding the feature, we teach how to use it instead, place examples and document why it is needed. (In most cases, the lifetimes present in public types won't be visible at all in usercode.)

This is the reason I mentioned that "it'll probably result in a completely different (but still simple and easy to use) crate". We expected that the implementation would change key points about ggez, and if you're not fine with these, it's ok, we'll just take the alternate path.

As for the actual lifetimes, `Text` is meant to be an inmediate object (Create, use, destroy; not stored) so the lifetime makes sense there; This is to avoid unnecessary data duplication. Having a `String` would mean that it would own the data it is referencing to, which is not always the case (The text, for example, can come from some external source such as a translation, other struct, as a parameter, etc). `Canvas` refers to graphic context internals which don't really need an `Arc` since the lifetime is very straightforward: The graphical context always must exist before the canvas, so it checks out. (As for the depth image, we're changing that, image internal arcing was implemented after `Canvas`)

**Comment by nobbele** [comment]
`Text` is not meant to be an immediate object, it's meant to be able to be used as one, same thing with `Canvas`. If you look in the examples, you will see that it's a frequent pattern. You can still provide immediate usage for Text by using Cow and type aliasing `Text` to `TextRef<'static>` but I am not sure how that can be solved for Canvas.

>misusing reference counters everywhere

Very guilty of this lol. Your implementation gave me ideas on how to minimize Rc's in my own implementation.

**Comment by nobbele** [comment]
@aleokdev I looked at it a bit closer and discussed with PSteinhaus. Canvas being temporary does work now that an image is borrowed (much cleaner that way even); but Text should still be made without a lifetime (or default to 'static with Into<Cow> arguments). 

Another thing I have to comment on is Canvas taking a mutable reference for 'a to context. If the context is locked for the lifetime of the canvas, how are you supposed to render anything?

**Comment by jazzfool** [comment]
`Text` will be changed to be owned to aid with the transition to an internal draw queue in `Canvas`. N.B.: Text is still very much transient and not meant to be retained (as there's absolutely no reason to - shaping and rasterized glyphs can and should be cached separately). I believe making caching internal across the API (I have done the same with `Sampler`) will lead to less user confusion.

In terms of `Canvas`, it only borrows `GraphicsContext`, so all the other sub-contexts are still available during rendering (and `GraphicsContext` doesn't have any use to the user during rendering anyway). This was part of our plan to expose the sub-contexts directly to the user instead of having `module::function`-type methods.

**Comment by nobbele** [comment]
> This was part of our plan to expose the sub-contexts directly to the user instead of having module::function-type methods.

Would be better to put this in a separate PR tbh

**Comment by aleokdev** [comment]
> Would be better to put this in a separate PR tbh. I like the idea

I'll transfer the context changes to a separate branch and PR them then. It'll take a while.

**Comment by PSteinhaus** [comment]
@aleokdev @jazzfool First off, thank you for all that work. It looks really good and it addresses some old inherent problems of ggez, such as the batching situation and probably (hopefully) some difficulties with drawing text as well. If the examples can be shown to work just fine when adapted to your fork, then I'm more than willing to go with it.

I'm fine with Canvas being an immediate object. It just makes more sense when working with wgpu, I guess (or perhaps even generally). It should mostly be lightweight enough. There are some things to be improved/worked out a bit more, like that ugly dependency on `MAX_DRAWS_PER_FRAME`, or tiny things like `transform` being `glam::Mat4::orthographic_rh(...) * glam::Mat4::from_scale(glam::vec3(1., 1., -1.))` instead of just `glam::Mat4::orthographic_lh(...)`, but all in all it should work (again, as long as it's true that the examples can be reimplemented without some major pain coming up).

I'm unsure though about forcing users to always handle the necessary `ScreenImage`s themselves. I feel like it could be a bit more comfortable to just store the main frame-ScreenImage in the graphics context, so that
```rust
let frame = self.frame.image(&ctx.gfx);

let mut canvas = Canvas::from_image(
    &mut ctx.gfx,
    CanvasLoadOp::Clear([0.1, 0.2, 0.3, 1.0].into()),
    &frame,
    None,
);
```
could be simplified into something more like
```rust
let mut canvas = graphics::frame_canvas(&mut ctx.gfx, CanvasLoadOp::Clear([0.1, 0.2, 0.3, 1.0].into()));
```
removing a bit of boilerplate together with the responsibility for users to even think about `ScreenImage`s if they don't want/need to.

Text is a different thing though. Canvases have been a slightly more advanced feature that many people didn't use and probably still won't use in their small toy projects, outside of having to create one to draw onto in their draw loop. Text, on the other hand, is something that almost any project ends up using. And while it's true that lifetimes are an important feature of Rust and that teaching to use them properly is a noble thing to do, I am also of the opinion that there are more than enough other things to learn when you're just starting out. And one of the main uses of ggez has always been as a playground for people just starting out in Rust, trying to dabble with something graphical and interactive. I'd hate to alienate them by throwing lifetimes in their faces, even if they don't end up in user code, usually.
That being said, I don't think that this would need to happen. Creating an example showcasing how to properly use Text, together with an explicit explanation of the lifetime in the docs of `Text`, linking to it, (or giving another short example in the docs themselves) might just be enough to not irritate people, though I'm sure many will still try to just store `Text`s in their state and some will then be irritated anyway, no matter what the docs and examples say...

**Comment by PSteinhaus** [comment]
Changing the API so much will cost us some compatability, but ggez's current API is far from perfect, so as long as the changes are for the better, necessary and don't leave the API looking too confusing or unfamiliar, then it's worth it. Reshaping things, modularizing the context, etc. has long been overdue.

**Comment by jazzfool** [comment]
@PSteinhaus Thanks for the feedback! I agree with all your points.

So, `MAX_DRAWS_PER_FRAME` was just a WIP thing, it should be removed soon. I also agree with the `ScreenImage` concern, having that main `ScreenImage` and main `Canvas` that needs to be declared every time is pointless. Overall, there are still some quirks in the implementation that should be ironed out soon.

As for text, the idea originally was that the lifetime wouldn't even be noticeable to the user as it would never be bound to a variable. In some cases though, users may want to pass around `Text` and that lifetime can get in the way, so I think we can make `Text` fully owned.

**Comment by PSteinhaus** [comment]
Having `Text` use a `String` instead of a `&str` is surely less efficient and as such it pains my little nerd heart to advocate for it, but in the case of ggez I just think that it'll make things easier for newbies and in that it's completely worth it to me to lose that tiny tiny bit of elegance/performance.

**Comment by jazzfool** [comment]
Using `Cow<'a, str>` is a great idea. I've implemented it on the branch. The `MAX_DRAWS_PER_FRAME` limitation has been removed and canvases can now be created with `Canvas::from_frame` without needing a `ScreenImage`.

I think it may also be appropriate to now tackle Z ordering of draws while I'm at it. Right now `Canvas` doesn't queue draw calls, so @aleokdev proposed that the priority queue could be implemented as a *separate* abstraction working alongside or on top of `Canvas`. It'd be great to hear your thoughts on this.

**Comment by PSteinhaus** [comment]
Hmm, why would you want to implement it as a seperate thing, instead of just inside of `Canvas`? After all, everything gets rendered to it, right? So where else would you want to use it?

**Comment by jazzfool** [comment]
Agreed; a unified drawing interface would definitely be the way to go. In that case, the current `Canvas` could probably be internalized/wrapped into a new priority queue `Canvas` type that delegates to the internal canvas. This should also help alleviate (if not completely eliminate from the public API) the strenuous lifetimes that `Canvas` demands.

**Comment by PSteinhaus** [comment]
Could you go into a bit more detail on what you mean by wrapping it in another Canvas type? Wouldn't such an object need to be recreated every frame (borrowing the graphics context and therefore having a lifetime), or else own all of the graphics context itself?
What exactly is the problem that you'd want to solve with it? The problem of which `Canvas` gets drawn first (sorting them by some kind of priority instead of relying on the order in which their draw calls where placed in the command encoder?)?

Or do you mean just a very simple wrapper type holding the `Canvas` and then the priority queue, to avoid placing the latter in the former? It's not obvious to me why just placing the priority queue inside of `Canvas` should be bad, as it's really an integral part of it, necessary to handle all draw calls made on it.

**Comment by jazzfool** [comment]
The latter; I was thinking a lightweight wrapper. I was testing out having a priority queue directly inside `Canvas` and the problem is working it into the state changes. When reordering draws, changes to the draw state (e.g. sampler) won't be in the same order. I believe it'd be easier to have an internal API boundary between immediate draw calls and deferred draw commands to deal with state changes in two different ways - I believe this may be cleaner to maintain in the future, but either choice is okay at the end of the day.

**Comment by PSteinhaus** [comment]
Ah, yes. That queue should remove the necessity for lifetime annotations, right.

These difficulties in keeping the state consistent sound a bit more complicated though. I still haven't grasped all of your code yet, so could you maybe elaborate a little more on what exactly goes out of sync and how these two kinds of draw calls would help to alleviate that problem?

**Comment by jazzfool** [comment]
Certain state changes such as the sampler and shader are like signposts in the GPU timeline to switch pipeline/bind groups/etc. If the draw calls are reordered then what could happen is that some of the draws that came after the switch to, say, sampler A, are now before it, and some other of those draws now come after some other sampler that isn't sampler A, etc. The deferred canvas would need its own method of state tracking by attaching some light state information to each draw call so that before it sends off the actual draw calls to the internal canvas, it can do its own state tracking in order to:

1. ensure that the shader/sampler/etc are all in the correct state for the upcoming draws
2. not make unnecessary state changes

I hope that made sense.

**Comment by PSteinhaus** [comment]
Yes, that makes sense. If the order of draw calls no longer depends upon when they were made, but with which z-values, then we can't depend upon that logic for pipelines etc. either and instead have to add some additional information about the intended context to each draw call.
