### ISSUE TITLE
More demo's/examples

### ISSUE THREAD

**Issue by Maplicant** [ggez/ggez#103]
I always really enjoy reading thoroughly-commented demo's instead of documentation. And more demo's never hurt! [Here's a demo I made](https://github.com/Maplicant/purplerain), not sure whether you'd like to use that.

**Comment by icefoxen** [comment]
Oooooh, shiiiiiny.

The problem is that eventually we have to maintain examples/demo's, and that takes time.  Ideally we'd have a minimal set of examples that clearly shows off every feature ggez has in a progressive and practical fashion.  Hmmm.

In lieu of that, perhaps we could create a list of projects that use ggez in the docs directory?  Then people could submit PR's to add their own...

**Comment by icefoxen** [comment]
We now have a [projects file](https://github.com/ggez/ggez/blob/master/docs/Projects.md).  This is a bit of a ghetto way of doing it for the moment; ideally we'd have a section on the website for this.  But for now, this is quick and easy.

**Comment by Maplicant** [comment]
Yeah I have to agree with that. This seems like a good solution until we have more minimal demo's!
