### ISSUE TITLE
MeshBuilder example for drawing a circle doesn't compile

### ISSUE THREAD

**Issue by EstiaanJ** [ggez/ggez#1048]
**Problem**
MeshBuilder example for drawing a circle doesn't compile
https://docs.rs/ggez/latest/ggez/graphics/struct.MeshBuilder.html
Even if I add glam to my dependencies, I still get errors. However it's not mentioned anywhere in the example that glam is needed.

So without glam I get the error:

```
error[E0433]: failed to resolve: use of undeclared crate or module `glam`
  --> src/main.rs:43:64
   |
43 |         let mesh = MeshBuilder::new().circle(DrawMode::fill(), glam::vec2(60.0,38.0), 50.0, 0.0, Color::WHITE)?;
   |                                                                ^^^^ use of undeclared crate or module `glam`
```
With glam 0.8.5 added I get
```
error[E0277]: the trait bound `Point2<f32>: From<Vec2>` is not satisfied
   --> src/main.rs:43:64
    |
43  |         let mesh = MeshBuilder::new().circle(DrawMode::fill(), glam::vec2(60.0,38.0), 50.0, 0.0, Color::WHITE)?;
    |                                       ------                   ^^^^^^^^^^^^^^^^^^^^^ the trait `From<Vec2>` is not implemented for `Point2<f32>`
    |                                       |
    |                                       required by a bound introduced by this call
    |
    = help: the following implementations were found:
              <Point2<T> as From<Vector2<T>>>
              <Point2<T> as From<[T; 2]>>
              <Point2<f32> as From<glam::vec2::Vec2>>
              <Point2<f64> as From<glam::vec2::DVec2>>
            and 2 others
    = note: required because of the requirements on the impl of `Into<Point2<f32>>` for `Vec2`
note: required by a bound in `MeshBuilder::circle`
   --> /home/estiaan/.cargo/registry/src/github.com-1ecc6299db9ec823/ggez-0.7.0/src/graphics/mesh.rs:112:12
    |
112 |         P: Into<mint::Point2<f32>>,
    |            ^^^^^^^^^^^^^^^^^^^^^^^ required by this bound in `MeshBuilder::circle`
```

**To Reproduce**
Add this code (from the example) to the default GGEZ example's draw loop:
```
let mesh: Mesh = MeshBuilder::new()
    .line(&[glam::vec2(20.0, 20.0), glam::vec2(40.0, 20.0)], 4.0, (255, 0, 0).into())?
    .circle(DrawMode::fill(), glam::vec2(60.0, 38.0), 40.0, 1.0, (0, 255, 0).into())?
    .build(ctx)?;
```

**Expected behavior**
Draw a circle

**Hardware and Software:**
 - ggez version: 0.7
 - OS: Linux Ubuntu 21, Intelij IDE
 - Graphics card: Nvidia GTX 1660 Mobile
 - Graphics card drivers: Vendor provided 

**Possible solution**
Add all dependencies to examples

**Comment by nobbele** [comment]
Is it one of those version mismatches?

**Comment by PSteinhaus** [comment]
I think so. [ggez 0.7 uses glam 0.20](https://github.com/ggez/ggez/blob/16497940f865296556784b06dce1d03171a41849/Cargo.toml#L59), which could explain the mismatch with glam 0.8 here.

Most of our examples use glam, a direct dependency of ggez. But you can use any other kind of math library you want, as long as it supports the same version of `mint` that ggez uses, which in the case of 0.7 is `mint 0.5`. Also, take care that you enable the `"mint"` feature on `glam`, if you use it.

You don't have to use glam, or anything like it, at all though, if you want. You can also just work with the types provided by the `mint` that gets re-exported with ggez, [like here](https://github.com/ggez/ggez/blob/16497940f865296556784b06dce1d03171a41849/docs/guides/GenerativeArt.md#-the-circle).

In `0.8.0-rc0` this problem is gone, as the example is gone too... I think porting the example would be a good idea. I remember having used this example while learning ggez back in 0.5 myself.

**Comment by EstiaanJ** [comment]
Thanks for the detailed explanation :)
