### ISSUE TITLE
Canvas::from_image not working properly for images smaller than window size (patch included)

### ISSUE THREAD

**Issue by nacl42** [ggez/ggez#1051]
**Description**
Using an intermediate canvas for drawing, created by `Canvas::from_image(..)`, will under certain circumstances cause an error such as the following:

```
Caused by:
   In a RenderPass
     note: encoder = `<CommandBuffer-(0, 1, Vulkan)>`
   In a set_scissor_rect command
   Invalid ScissorRect parameters
```

**To Reproduce**
This bug will only occur, if you create the Canvas from an image which has a size smaller than the current window.

Tested on ggez-0.8.0-rc0.

**Solution**
I googled around for the set_scissor_rect error, along with `wgpu` and found some hints that this might happen, if the `scissor_rect` is larger than the image size. Based on this hypothesis, I modified the ggez code. I found the corresponding part in 'ggez/src/graphics/canvas.rs' in the function `new` and changed it as follows:

```
- scissor_rect: (0, 0, drawable_size.0 as _, drawable_size.1 as _),
+ scissor_rect: (0, 0, target.width() as _, target.height() as _),
```

The existing assignment would always use the size of the drawable, which is basically the size of the window.

You also need to adjust the `screen` a few lines later on:

```
- w: drawable_size.0 as _,
- h: drawable_size.1 as _,
+ w: target.width() as _,
+ h: target.height() as _,
```

I am not sure if this is really fixed the cause or is just a fix by coincidence, but it sure worked for me.

Sorry for not sending in a proper pull request, but I am not so familiar with this and I thought it might be better to contribute this way than not at all.

**Comment by nobbele** [comment]
Thanks for reporting this!

It looks like drawable_size is screen size rather than image size, I wonder why.

**Comment by PSteinhaus** [comment]
Thanks indeed. This is an important bug and I believe your patch to be correct.

> It looks like drawable_size is screen size rather than image size, I wonder why.

drawable_size being screen size might make some sense in case of `screen`, as I believe that's how `Canvas` has worked until now: Even if you draw on a `Canvas` your coordinate system stays the same as when not drawing to one, [which leads to undesired effects when not aware of this](https://github.com/ggez/ggez/issues/863). (Or indeed as seen here, since @nacl42 points out that the `screen` lines have to be changed as well to get the result you'd intuitively expect.)

I think it might be time to change this though. I don't really see a point in this, now that drawing has moved to be always canvas-bound anyway and coordinate systems are administrated per canvas instead of globally.

using `drawable_size` for `scissor_rect` makes absolutely no sense though. I think this was simply an oversight. Of course we need to use the target dimensions here.
