### ISSUE TITLE
Vectors should be included in the framework.

### ISSUE THREAD

**Issue by Asmageddon** [ggez/ggez#106]
They're an extremely basic building block of video games, and almost every project is going to (re)implement them.

Not including them will only reduce ease of integration between libraries, increase code duplication and the amount of work that has to be done when setting up a project.

**Comment by icefoxen** [comment]
You're not wrong.  The thing is, there's many good Rust libraries out there that already include vectors: `cgmath` and `nalgebra` and `euclid`.  They will implement vector math better than we will, and do a better job of making those implementations really good.  So it seems more sensible right now to allow you to use whichever of those strikes your fancy, rather than providing a crappy version or forcing you to use any particular one.

Better interoperability would be nice, I agree.  That's a goal of the [mint](https://github.com/kvark/mint) crate, but it's early days for that yet.

**Comment by Asmageddon** [comment]
In that case, why not include one of those libraries, or part of one? If there's possibility of wanting to swap the implementation out at a later date, a shim could be used.

**Comment by svenstaro** [comment]
I see the points of both parties but I side with @Asmageddon a bit because of ggez's philosophy: It is actually opinionated and we shouldn't be another piston (no offense piston people!) where we have too many loose components to be a good choice for starters. We should probably just pick something and run with it (not perhaps not build too much stuff on top of it).

Every game probably needs a vector library at some point. I only have experience working with nalgebra so far and it's pretty sweet but 3/5 on a difficulty scale.

**Comment by icefoxen** [comment]
Ok... given that we have `Point`'s and `Rect`'s already, you're certainly not wrong.  Thinking about how to implement this though...  My first impulse would be to pull in nalgebra and add some shortcuts and wrappers to its types to present a slightly simplified interface.

The question then is, how far do we want to go with this?  Mainly, do we want to have a physics engine?  (nphysics, I suppose?)  Because our choices for vector math stuff will affect how well that interoperates.

**Comment by Asmageddon** [comment]
I'm not really actively developing anything in Rust, but you could always go for Box2D/Chipmunk. They're not Rust libraries(although I'm sure bindings exist), but they're good, proven solutions.

Also, you'll never get anything done if you overthink things too much(speaking from personal experience) - sure, some people might want a different vector lib, but is that really worth potentially harming code reuse/sharing?

**Comment by icefoxen** [comment]
> Box2D/Chipmunk

Adding more large-ish C dependencies is not going to make life simpler.  Especially when the bindings for said libraries are on version 0.0.2 and were last updated a year ago.

>  is that really worth potentially harming code reuse/sharing?

Yes, if it actually makes future code reuse/sharing harder.  This is not a case for "do the obvious thing" because it's very fundamental and will affect how lots of parts of the library works.  This means changing it in the future is going to be a lot of work, and is going to be a PITA for anyone actually using ggez (ie, me).  This is a case for "measure twice, cut once".

I hesitate to make decisions for users unless it's obvious what the decision *should* be.  This might be me being over-conservative.  For using, say, `rodio`?  Ok, there's one good option that's pure rust, go ahead and use it.  Math?  Three different solutions, all good, or we could write a fourth one!

**Comment by svenstaro** [comment]
The advantage of using nalgebra would be that then using nphysics (which is the only purely rust physics engine that I know of) would be a breeze.

**Comment by icefoxen** [comment]
Actually, the [euclid](https://docs.rs/euclid/0.15.1/euclid/) crate might be worth looking at.

Advantages: 

 * It's part of servo so it's probably going to continue being maintained well
 * It has some nice convenience for 2D stuff, such as types for rect's
 * It's quite easy to understand, starting from a practical basis instead of nalgebra's more theoretical approach
 * It's used by `lyon`, which is something we already use

Disadvantages:

 * All its types have a unit attached to them, which is a bit of clutter for our purposes
 * Not as popular as nalgebra or cgmath
 * nalgebra is awesome
 * Makes life harder if we want to interop with nphysics

**Comment by Object905** [comment]
Here are my two cents.

I can say that `nalgebra`'s hard for a newcomer in terms of API because it heavily uses generics, a lot of unit types to handle generics, generic bound on functions and it even provides ways to provide generic allocator. It aims to be general purpose linear algebra library, so, as stated above it has more theoretical approach, thus there will be a lot of unneeded features for a 2D game engine. Also while it has the nice user guide, but it takes a time to get into, even if you just wanted to do some simple things. As the main advantage, I see `nphysics` crate integration.

`cgmath` in the other hand has much simpler API and aims to be computer graphics specific, but there is no physics library that I know (although it has `collision` library).

At first glance `euclid`  seems to me a good chose, in terms of ease to use and ergonomic, and it should meet basic requirements. Also, it's not actual linear algebra library, but a collection of math tools for CG with the focus on 2D, which is, in my opinion, good, because it just consist's of "basic building blocks", more intuitive and doesn't base on mathematical properties. Also, it used in `webrender` and `lyon` which inspires confidence. Regarding unit type: it might be useful, and there is a bunch of type aliases with default one.

**Comment by icefoxen** [comment]
@svenstaro I'm going to have time to start doing this in the relatively near future, and I'm leaning towards euclid pretty heavily at the moment (though the nphysics connection for nalgebra *is* really tempting).  Any opinions on which we should go for?

**Comment by svenstaro** [comment]
I had a look at euclid and I'm not sure what it would add. I think the API is about as hard as that of nalgebra and certainly harder than cgmath. If anything, I'd prefer cgmath but the ncollide and nphysics aspects are too good to be honest. So unless there are really good reasons for euclid, I think nalgebra should be preferred. I think having physics "just work" is both in line with the game engine's philosophies and it'd also be a killer feature.

**Comment by svenstaro** [comment]
Alternatively (and perhaps weirdly) we could also just expose cgmath to the user and internally convert to euclid for lyon and to nalgebra for nphysics. This sounds silly, of course, but it's a possiibility.

**Comment by icefoxen** [comment]
I don't see what you mean that the euclid API is about as hard as nalgebra...  The 2d parts of it at least seem very straightforward.

In terms of converting types, that's the sort of thing that kvark is creating the [mint](https://crates.io/crates/mint) crate for.  But, it does seem like something to avoid unless we really need to.  lyon doesn't *need* its inputs in any particular form, it just uses euclid internally.  I was just looking at cargo build dependencies and said "wait a second, we already include a math library", which made me look at euclid more closely.

nalgebra being used for nphysics really is kind of a killer feature, I confess.  I'm a little scared because nphysics is an ambitious project currently in very early stages... but even without it, ncollide is perfectly usable and awesome.

So.  If you say "I'd prefer cgmath" and I say "I'd prefer euclid", should we meet in the middle and go with nalgebra for the hopes of an awesome physics engine?  :-P

I should note that whichever we choose, this won't actually affect the *internal* functioning of ggez much at all, yet.  Like I said at the beginning, literally all we need is point and rect types.  It won't be terribly hard to change from one library to another; it's mostly a matter of what API we expose to our users.

**Comment by svenstaro** [comment]
Alright, let's roll with nalgebra as a conservative bet for now. As you say, it's likely not too hard to change this out later on.

**Comment by icefoxen** [comment]
Started a branch that uses nalgebra. It vaguely annoys me because it has no good way to turn types into arrays and back, but it definitely works.

**Comment by svenstaro** [comment]
Maybe report an upstream bug and see? I think the nalgebra author is rather responsive.

**Comment by icefoxen** [comment]
This is more or less done as of 0549bf9d54f2cdcd7a4439fa18319f8ce515c633 , just needs review.

**Comment by icefoxen** [comment]
Oh, nalgebra bug reported in https://github.com/sebcrozet/nalgebra/issues/286 also

**Comment by icefoxen** [comment]
Update: This has been pushed to master and all the examples updated to use it.  nalgebra currently is re-exported from `ggez::nalgebra`, and the `Point` and `Vector` types in `ggez::graphics::types` have become nalgebra `Point2<f32>` and `Vector2<f32>`.

Seems to work out well but I'm not closing this until I'm pretty sure I'm not forgetting anything.  One thing we might want to consider is re-exporing nalgebra from `ggez::math` instead of `ggez::nalgebra`, which feels more tidy but is also potentially ambiguous.

**Comment by icefoxen** [comment]
I've used this for a week and a half now and don't hate it yet.

**Comment by dbrgn** [comment]
As another datapoint: This is how my journey of discovering 2D geometry with ggez was:

- ggez reexports nalgebra, so let's try that
- I want to store a point, so let's search for a type at https://docs.rs/nalgebra/
- Point2 looks suitable: https://docs.rs/nalgebra/0.14.1/nalgebra/geometry/type.Point2.html
- So what is a Point2? It's a Point<N, U2>: `type Point2<N> = Point<N, U2>`
- Let's look at the docs for `Point`. https://docs.rs/nalgebra/0.14.1/nalgebra/geometry/struct.Point.html It contains coordinates which is a vector. Fair enough.
- So how do I create such a `Point2`? The docs for the `Point2` type don't turn up anything when Ctrl+F for `fn new`.
- When searching through the `Point` docs on the other hand, the search turns up something. Actually, 6 different versions of `new()`. Apparently one for each dimensionality. Fair enough.
- So I guess I create a new point using `Point2` using `Point::new(x, y)`. But what type are `x` and `y`? I'd assume `f32` or `f64` (although they might be integral too for certain use cases).
- The `Point` is generic over a type `N`. Maybe that's the coordinate type. N implements `Scalar`: https://docs.rs/nalgebra/0.14.1/nalgebra/core/trait.Scalar.html
- So what is `Scalar`? The docs don't really tell me. The trait is implemented for every type `T` apparently. The `is` method documentation mentions something about `f32` and `f64`, so it can probably be both. I still don't know if integers would be accepted.
- Ok, so let's create a new `Point2` with `Point::new(0.0f32, 0.0f32)`. Now I want to get the X coordinate. Looking through the docs, I find nothing appropriate after a quick glance. The type impls about 146 traits though, maybe one of them provides access to coordinates? But which one?
- That sounds complex. Let's instead access the underlying vector. The `coords` type is a `VectorN<N, D>`.
- The docs for [`VectorN`](https://docs.rs/nalgebra/0.14.1/nalgebra/core/type.VectorN.html) contains a `x()` method. Maybe that gives us the `x` coordinate? No, according to the method docs, that creates a new unit vector.
- So what's a `VectorN` exactly? Can I access its fields? Oh, it's a `MatrixMN<N, D, U1>`.
- Ok, a vector is a specific type of matrix. Fair enough. So what's a `MatrixMN`?
- A `MatrixMN` is a [`Matrix<N, R, C, Owned<N, R, C>>`](https://docs.rs/nalgebra/0.14.1/nalgebra/core/type.MatrixMN.html). Holy shit, I give up.

So in summary, `ggez::graphics::Point2` is a `nalgebra::geometry::Point2<f32>` which is a `nalgebra::geometry::Point<f32, U2>` which contains a `nalgebra::core::VectorN<f32, D>` which is a `nalgebra::core::MatrixMN<f32, D, U1>` which is a `nalgebra::core::Matrix<f32, R, C, Owned<f32, R, C>>`. And I still don't know how to access the X and Y coordinate of a simple point.

I realize that nalgebra has some very compelling advantages, like good performance, n-dimensionality, integration with nphysics, etc. But in the end, ggez seems to focus more on simplicity than on generality, right? For example, it's primarily aimed at 2D graphics becaues that's simpler. Then why include an n-dimensional linear algebra library if an algebra library aimed at computer graphics with 2- and 3-dimensional types would work just as well?

I think [cgmath](https://docs.rs/cgmath/0.16.1/cgmath/) could be a good fit. It's optimized for computer graphics and provides very convenient functionality like a `From<[f64; f64]>` impl for the `Vector2` type or `.x` and `.y` accessors on `Vector2`.

I've never used `euclid` so I have no opinion on that.

Summary: I'm not an expert on linear algebra or linalg libraries at all, but nalgebra seems overly complex for ggez.

**Comment by termhn** [comment]
So, uh... did you try just doing `.x` and `.y`? :P You can absolutely do, say: 

```rust
let mut my_point = ggez::graphics::Point2::new(0.0, 0.0);
my_point.x = 10.0;
my_point.y = 15.0;
```

**Comment by svenstaro** [comment]
@dbrgn I entirely agree and I also thought about ways to fix that. I thought perhaps a "simple layer" on top of nalgebra?

**Comment by dbrgn** [comment]
@termhn whoa, where can I find that in the docs? :)

**Comment by dbrgn** [comment]
@svenstaro but in general, why does ggez need an n-dimensional linear algebra library if a 2/3-dimensional library would simplify the API a lot? especially since it only seems to be used for simple things like points and vectors and transformation matrices.

**Comment by svenstaro** [comment]
@dbrgn Mainly because it makes integration with a physics engine really easy (ncollide and nphysics) and because those are really darn good. That was a hard trade-off to make but I believe it's easier than forcing people to layer their own nalgebra on top if we had gone with cgmath.

**Comment by termhn** [comment]
> @svenstaro but in general, why does ggez need an n-dimensional linear algebra library if a 2/3-dimensional library would simplify the API a lot? especially since it only seems to be used for simple things like points and vectors and transformation matrices.

The main consideration here was originally that the best/only physics library was being written using nalgebra and having easy interop with that would be great. However I believe that there's now Rhusics, which, while less complete than nphysics currently, is using cgmath and is being designed to work excellently with specs (it's being developed for use in Amethyst). So... that's no longer really a big reason.

I'd be open to the suggestion of converting over to cgmath, but... idk.

> @termhn whoa, where can I find that in the docs? :)

Honestly no clue haha, never looked in the docs for it

**Comment by icefoxen** [comment]
I would in principle be okay with cgmath but honestly don't feel that it's actually that much simpler than nalgebra when you get a little beyond vectors and points. I totally agree that the nalgebra API docs are a morass; the best way to learn nalgebra is to read the tutorial on the nalgebra website, but for something simple it's really easy to try to go through the API docs instead.

For the x/y stuff, Vectors can deref into [this](https://docs.rs/nalgebra/0.14.3/nalgebra/core/coordinates/struct.XY.html).

Throwing `Into<MintType>` everywhere solves this with a nice layer of abstraction but just makes life complicated in a different way! It's easy to document with examples but I don't know where we would put it so that everyone always sees it.

**Comment by ozkriff** [comment]
> but honestly don't feel that it's actually that much simpler than nalgebra when you get a little beyond vectors and points

But that's all that you usually want for some simple 2d games?

I've seen some similar journeys [to the above-mentioned one](https://github.com/ggez/ggez/issues/106#issuecomment-388488407) in russian gamedev community.

nalgebra is very disproportionately complicated part of ggez. Like, "here, comrad, take a look at this simple game engine over here - oh, i can really make some demo with that! But how do I" - and them BOOOOM and all the MatrixMN VectorN etc things happen and a newbie looks shocked at giant signatures with zillions of traits:

![](https://i.imgur.com/x4yz7Fum.png)

**Comment by Ratysz** [comment]
I think this could be solved by exporting simple aliases of all the types we want (there's, what, 3 of them?), be they from `nalgebra` or `cgmath` or whatever, and documenting them with info on their most common uses and methods. AFAIK, docs will automatically inject a link to the original type, as well. This way we get to keep simplicity and compatibility (with an escape hatch to original lib's power/complexity), without having to actually implement anything.

There might be a better, semi-automatic way of selectively documenting such aliases, too, but I can't recall where that was mentioned.

**Comment by icefoxen** [comment]
Exporting simple aliases is easy... that's more or less what we already do.  Documenting them is the hard part!  Especially when we start to consider things that are somewhat advanced or fiddly, like "why can you call `norm()` on a vector but not a point" or whatever.

**Comment by icefoxen** [comment]
As of commit 200ce3e this is mostly done; there's some lingering places where `Point2` and `Vector2` are used and we should hunt them down and destroy them.  Mostly though, every function that took `Point2` now takes `Into<mint::Point2<f32>>` and so on, and every type where they were exposed directly (I THINK) now is a builder instead.

This means that you can write your game using either `cgmath` or `nalgebra` with the `mint` feature enabled, as demonstrated in the `hello_world` and `astroblasto` examples in that commit.

**This does have a cost**.  More generics make the API harder to grok, and slow down compile time.  Given that some people get understandably grumpy at `nalgebra` for its 10th level black belt use of generics at every opportunity, this makes me a little cautious about this change still.

But, it's actually pretty awesome to use.

**Comment by icefoxen** [comment]
I like using mint a lot now, so we're keeping it until it confuses too many people.
