### ISSUE TITLE
is_key_just_pressed not working as expected

### ISSUE THREAD

**Issue by Sharmiko** [ggez/ggez#1064]
**Describe the bug**
I am trying to detect key tap using `is_key_just_pressed`, but it does not work as expected, `is_key_pressed` is detected instead. Output is also undeterministic, when I press key repeatedly, most of time `pressed` is printed, but sometimes `just pressed`, code below.
```
pressed
pressed
pressed
pressed
just pressed
pressed
pressed
pressed
pressed
pressed
pressed
pressed
pressed
pressed
pressed
pressed
just pressed
pressed
pressed
pressed
pressed
just pressed
pressed
pressed
```

**To Reproduce**
```rust
if _ctx.keyboard.is_key_just_pressed(KeyCode::F) {
    println!("just pressed");
} else if _ctx.keyboard.is_key_pressed(KeyCode::F) {
    println!("pressed");
}
```

**Expected behavior**
When pressing some key I expect first if statement to be executed instead of second. 

**Hardware and Software:**
 - ggez version: 0.8.0-rc0
 - OS: Manjaro Linux 21.3.1 Ruah
 - Graphics card:  NVidia RTX 3060
 - Graphics card drivers: Vendor provided driver, Driver Version: 515.48.07

**Comment by PSteinhaus** [comment]
I just tested it and can't reproduce that.

Are you sure you don't mix these outputs up?
Could you try printing the current engine tick with it, like this?
```rust
if _ctx.keyboard.is_key_just_pressed(KeyCode::F) {
    println!("cycle {}: just pressed", ctx.time.ticks());
}
if _ctx.keyboard.is_key_pressed(KeyCode::F) {
    println!("cycle {}: pressed", ctx.time.ticks());
}
```
I get somthing like this:
```
cycle 2046: pressed
cycle 2046: just pressed
cycle 2047: pressed
cycle 2048: pressed
cycle 2049: pressed
cycle 2050: pressed
...
cycle 2973: pressed
cycle 2973: just pressed
cycle 2974: pressed
cycle 2975: pressed
cycle 2976: pressed
cycle 2977: pressed
cycle 2978: pressed
cycle 2979: pressed
...
```

**Comment by Sharmiko** [comment]
Okay I found out what was causing this behavior, but not sure why it is happening. For my game I am limiting fps to 10. When I tried to run keyboard input check code without fps limit it works as expected, but inside this loop sometimes it won't detect just pressed event. 

```rust
    fn update(&mut self, _ctx: &mut Context) -> GameResult<()> {
        const DESIRED_FPS: u32 = 10;
        while _ctx.time.check_update_time(DESIRED_FPS) {
            if _ctx.keyboard.is_key_just_pressed(KeyCode::F) {
                println!("cycle {}: just pressed", _ctx.time.ticks());
            }
            if _ctx.keyboard.is_key_pressed(KeyCode::F) {
                println!("cycle {}: pressed", _ctx.time.ticks());
            }
        }

        Ok(())
    }
```

**Comment by Sharmiko** [comment]
Do you have any suggestions, what should I do in this case? Thanks.

**Comment by nobbele** [comment]
I'm not sure its the best way but in my own game I have a queued_attack variable that gets set on just pressed in update and unset on handle in fixed update

**Comment by PSteinhaus** [comment]
> Okay I found out what was causing this behavior, but not sure why it is happening. For my game I am limiting fps to 10. When I tried to run keyboard input check code without fps limit it works as expected, but inside this loop sometimes it won't detect just pressed event.

The reason is that `is_key_just_pressed` tells you whether a key was _just_ pressed, which means in the current cycle, not a couple cycles ago.

To do something like that we'd have to reset the set of "just pressed keys" inside of `Canvas::finish`, or something like that. (Which wouldn't work as soon as two canvases are used...)

You can achieve it yourself, if really necessary/desired, by creating your own event loop and calling [`save_keayboard_state`](https://docs.rs/ggez/0.8.0-rc0/ggez/input/keyboard/struct.KeyboardContext.html#method.save_keyboard_state) (which we should probably rename to just `save_state` now that I think of it) whenever one of your frames ends.

Other than that, @nobbele 's suggestion is perfectly workable as well. You just have to decide whether you'd rather implement a small tracking mechanism like that, or roll your own event loop (which isn't _that_ hard as well; you can start with the `eventloop` example and then basically fill in the missing parts from [`event::run`](https://github.com/ggez/ggez/blob/f6c34de7a14859bef05d02aef8a2e12d2b6fc19e/src/event.rs#L294), calling everything after `tick` based on `check_update_time`).
