### ISSUE TITLE
Support for empty string rendering

### ISSUE THREAD

**Issue by arteme** [ggez/ggez#109]
The current behavior when an empty string is passed to ``graphics::Text::new`` is to attempt to render 0 characters, which tries to allocate a zero-width texture and fails. A developer is then forced to somehow work around this and validate all their strings. It would be nice if empty string would not fail rendering, but instead return some dummy graphics object (size 0x0) that can be safely passed to ``graphics::draw``.

**Comment by icefoxen** [comment]
It gets even worse because it does the same thing when you try to render a string that only contains whitespace, IIRC.  :D  Rusttype just says "oh well there's nothing to render there" and expects you to get on with life.

It should definitely not fail with an arcane gfx-rs error when you do this, yes.  I'm a little suspicious of the dummy-graphics-object solution, because you have to end up with a lot of methods like `get_filter()` that suddenly have no meaning and have to either return nonsense or... something.  Still, it might be the best way.

Returning an `Option` that is `None` when there is no text to render is the most convenient solution from the library side, but that really just pushes the problem of detecting and handling this case off to the user, instead of solving the problem.  I'm currently leaning towards making `Text.texture` an `Option<Image>` instead of an `Image`, and having the methods that touch it occasionally return nonsense, but I want to think about this a bit more.

**Comment by icefoxen** [comment]
Fixed; we just create a blank 1-pixel-wide texture instead.  This is a little bit of a hack but also makes sure all behavior is 100% consistent and puts the special case in only one spot.  (Well, two spots; bitmap fonts have the same issue.)
