### ISSUE TITLE
conf::WindowMode takes pixel size not LogicalSize which makes creating windows that scale in high res difficult

### ISSUE THREAD

**Issue by chamons** [ggez/ggez#1091]
**Describe the bug**

My development machine has a high DPI screen, as requesting a window of 1024x768 produces a very tiny one, as the scale factor is 2.0. 

To combat this, I looked into querying winit with something like this:

```
    let event_loop = EventLoop::new();
    let scale = event_loop.primary_monitor().unwrap().scale_factor() as f32;
```
so I could scale the requested resolution, but having two event loops created causes a crash (even if I drop it first).

After [discussions on discord](https://discord.com/channels/273534239310479360/335502453371961344/1014684405291307039) a helpful Red Artist said the following:

> its honestly a ggez problem. winit takes `Into<Size>` which allows using LogicalSize, so that winit can scale the window on MacOS or high res monitors. 
> ggez instead takes a width: f32, height: f32 and uses them as PhysicalSize instead which will not scale. 

I believe [this](https://github.com/ggez/ggez/blob/master/src/graphics/context.rs#L113-L114) is the code in question, with [this](https://github.com/ggez/ggez/blob/master/src/conf.rs#L63-L67) being where it is setup is done in pixels.

**To Reproduce**

Create a new ggez project and run it with a config like this:

```
conf::WindowMode {
            1024,
            768,
            ..Default::default()
        }
```
on a high DPI screen. 

A 1024x768 window is about 1/3 of my laptop's screen in width. 

**Expected behavior**
Either the ability to request that my resolution be scaled by scale_factor or more correctly be able to provide something `Into<Size>` that is passed to winit directly. 

**Hardware and Software:**
 - ggez version: 0.8.0-rc0
 - OS: macOS 12.2.1 (but this is not a macOS specific bug)

**Comment by chamons** [comment]
The fact that every field in WindowMode being public makes this a bit tricky to fix (since I assume you would not want to break that simple width/height API), but I was thinking something like:

- Create an optional field in WindowMode like `raw_size` that is Option<Into<Size>> so a user can set a LogicalSize.
- In GraphicsContext::new use that raw_size if it is non-None, else the current width/height, possibly asserting if width/height is set to the non-default value (but that would require checking it two places, so I don't think it's worth it).

**Comment by chamons** [comment]
I am willing to PR a fix if you believe my approach is reasonable and high DPI support is desired.

**Comment by PSteinhaus** [comment]
Thanks for looking into this.

I think I agree that allowing logical window sizes instead of physical ones is something we ultimately want.
In the past though, we first spent some effort getting rid of them, as people got confused by them and mouse input was slightly annoying to get right once a scaling factor came into play. A little history of this process can be found here: https://github.com/ggez/ggez/pull/884

BUT, as there again and again are people who rightfully argue for the benefits of high-dpi scaling and desire ggez windows to behave like one would expect, based on the other windows/programs who usually _do_ scale themselves using the scaling factor, I see no reason to not give the option for logical sizes to those who know what they're doing.

How to achieve this best is a good question though.
Changing only the start-up behavior, allowing a `raw_size` (or maybe `logical_size`?) to be passed, would solve your immediate problem, but all other ggez functions would still return/work with physical sizes.
For example, using `GraphicsContext::set_drawable_size(600., 800.)` will return your window to a physical size of 600x800, without respecting the scaling factor whatsoever.

It would require a bit more work (and a bit of fiddling and increased maintenance effort), but we could add something like an additional config field `logical_sizes: bool`, which controls whether sizes are to be interpreted as logical or physical globally.

This would mean we'd have to give logical sizes to winit when setting the window size and we'd also have to query the logical size instead of the physical one when this flag is set.

It would also mean that we'd have to change the way `Canvas`es are created slightly, which currently use `drawable_size` as the starting value of their coordinate space. Now we'd have to query the logical window size and use that.

This, in turn, means that we'd have to apply the scaling factor somewhat by hand onto the mouse positions that are input, in order to make them consistent with this coordinate system (as mouse input is given in physical pixel coordinates).

-------

Ok... having typed this out I think I'd prefer the simpler solution of allowing a logical size to be given as startup configuration, as you proposed, and that's it. What do you think?

**Comment by chamons** [comment]
That sounds like a boatload of work, and work that could subtly break behavior along the way, but only on high DPI systems. 

I think an optional logical_size in startup configuration gets us 90% of the way there with a fraction of the work/risk and is the right call for now. 

If it is commonly use and people run into more pain it can be revisited.

**Comment by chamons** [comment]
I will take a stab at this.

**Comment by chamons** [comment]
PR is up. Let me know what you think.
