### ISSUE TITLE
Mesh `from_raw`

### ISSUE THREAD

**Issue by andrewbaxter** [ggez/ggez#1112]
There used to be a way to import vertices and indices directly, but AFAICT this isn't possible any more (intentionally?).

`from_data` takes `MeshData` which has private fields and can only be created via `MeshBuilder` which more or less exposes the same methods as `Mesh`.

I'm building a spline, and I think the only way to get the data into ggez is to
1. Build a path with `lyon`
2. Tessellate with `lyon`
3. Get the indices and vertices and convert to a vertex list with duplicated verticies
4. Convert the `LPoint` vertices into `Point2D` vertices
5. Pass to `triangles`, which converts the points from `Point2D` into `LPoint`
6. Turns the list with duplicate vertices into separate index and vertex lists with duplicate vertices

Aside from unnecessary conversions, unless there's a vertex deduplication step I didn't see this will also be less efficient in that regard too.

For my specific use case, I think exposing a path builder like lyon would work, but I imagine there may be other external systems people would want to import meshes from and a `from_raw` method would be very helpful.

As it is, the use case of `from_data` isn't particularly clear to me (except internally, in other methods).

**Comment by PSteinhaus** [comment]
I agree with you fully.
I remember a discussion about the purpose or not purpose of `MeshData` as a whole back then and I still can't really see why `from_data` should be public, except to allow for multiple instantiations of the mesh data held by `MeshBuilder` (which after that could be added on via additional method calls), but this could also be solved simpler without `MeshData`, by just making `MeshBuilder::build` create `Mesh`es directly.

`from_raw` is indeed something we should re-add, imo.

**Comment by PSteinhaus** [comment]
Ok, we just discussed this in the [new fancy Discord server](https://discord.gg/48VycPe2ZX) (which we'll properly feature with the release of 0.8.0) and nobbele kindly reminded me that [`MeshData`](https://docs.rs/ggez/0.8.0-rc1/ggez/graphics/struct.MeshData.html) _has no private fields_.

So you can create custom meshes just like you could before. It's just that you now create a `MeshData` struct with two fields instead of calling a function with two parameters.

We actually even do so in our own `03_drawing` example, I just realized 😅 :
https://github.com/ggez/ggez/blob/8052ded79ae0339d04923564db3e413e9d26c39b/examples/03_drawing.rs#L88-L116
