### ISSUE TITLE
renderpasses can be sabotaged by events earlier in the wgpu queue

### ISSUE THREAD

**Issue by Bowarc** [ggez/ggez#1129]
**Describe the bug**
Multiple draws & clear of a InstanceArray in a single frame draws only the last call

**To Reproduce**
I think `https://github.com/Bowarc/ggez0.8InstanceArrayBugSortOf` would explain wayy better that the following but.

let's call the first `ggez::graphics::InstanceArray` `IA1` and the second one `IA2`
if you use a `IA1` and `IA2` on a canvas, clearing the `IA1` and `IA2` and then using `IA1` on another canvas (In the same frame) it causes the first canvas to not show the draw of the `IA1` (**only** the `IA1`, `IA2` is not affected)

**Expected behavior**
I expected to see draws of `IA1` on both canvases

**Screenshots or pasted code**
I made a quick usable code of ~150lines so you can test it: https://github.com/Bowarc/ggez0.8InstanceArrayBugSortOf

i have a quick video of my game prototype where i got this bug for the first time
https://cdn.discordapp.com/attachments/898362796658532373/1037228027253366814/2022-11-02_05-52-14.mp4

**Hardware and Software:**
 - ggez version: 0.8.1
 - OS: Windows10
 - Graphics card:  NVIDIA GeForce RTX 2070
 - Graphics card drivers: Default W10 Nvidia driver, { version: 526.47,  release date: 10/27/2022 }

**Comment by PSteinhaus** [comment]
Meh, I can reproduce it.
Thanks for sharing and for the working example especially.

**Comment by PSteinhaus** [comment]
Ok, this is what happens:

1. When we draw an `InstanceArray` we're calling `flush_wgpu`, flushing the current `InstanceArray::uniforms` and `InstanceArray::params` to its wgpu buffers. Then we're cloning its buffer (also indices buffer) handles, giving them to wgpu.
2. When we're clearing that `InstanceArray` we don't clear these buffers directly, but clear `InstanceArray::uniforms` and `InstanceArray::params`.
3. When we draw it again (on a new canvas in this case, but that shouldn't matter) we again call `flush_wgpu` **overwriting** the contents of the wgpu buffer, so that the first draw is effectively overwritten/cancelled.

**Comment by PSteinhaus** [comment]
How to solve this I'm not sure immediately.
I also don't get why we didn't have this problem in 0.7 already. Our method is pretty similar there, just that it's even simpler with only one buffer for instance properties globally:
https://github.com/ggez/ggez/blob/dbd200c7d80a72fc062f8fbdf47c30c54fb42aa8/src/graphics/spritebatch.rs#L133-L144

Also, shouldn't calling `canvas.finish()` _finish_ the renderpass making all that comes after irrelevant?
After all, all things are pushing onto the same wgpu queue, so they should be executed in order, meaning the draw needing the buffer in the first state should also happen then, before the buffer change is then actually changed afterwards, preparing it for the second draw...

**Comment by PSteinhaus** [comment]
Now that we discussed it [on Discord](https://discord.com/channels/1031224392174293002/1031224393126387764/1037434249864810557) a bit it seems this problem is way worse and affects and cripples many more functions in ggez, namely ([copied from Discord](https://discord.com/channels/1031224392174293002/1031224393126387764/1037444634936356944)):
- `Image::to_pixels` and `Image::from_pixels_wgpu` (can be solved by "one-per-pass")
- `ShaderParams::set_uniforms` (can be solved by "one-per-pass" as uniforms to a shader can only be one way or another for one pass?? Or wait... you should be able to change uniforms and reuse the same shader for multiple draws in one render pass, right? If so, it can't be solved by "one-per-pass")
- `InternalCanvas::set_projection` (can't be solved by "one-per-pass")
- `InternalCanvas::flush_text` (not sure if this is a problem at all and whether it could be solved by "one-per-pass")
- `InstanceArray::flush_wgpu` (can't be solved by "one-per-pass", except if we say that an IA can only be drawn once per render pass, but that's annoying)

"one-per-pass" is the idea to create one command encoder per render pass and submit it to the queue on `Canvas::finish`.
As you can see it would solve some problems, but not all, sadly.

**Comment by jazzfool** [comment]
Whoops...
Fortunately this is a very simple fix; the graphics module uses `wgpu.queue.write_buffer` across the board (this was an oversight), which specifically states
> This method is intended to have low performance costs. As such, **the write is not immediately submitted**, and instead enqueued internally to happen at the start of the next submit() call.

So, to fix, changing out `wgpu.queue.write_buffer` to instead use [`StagingBelt::write_buffer`](https://docs.rs/wgpu/latest/wgpu/util/struct.StagingBelt.html#method.write_buffer) (there's already a StagingBelt instance in the graphics context) should do the trick, as it inserts the copy buffer commands in the correct position in the command buffer (and thus WGPU should place the correct memory barrier between the buffer copy and the render pass).

**Comment by PSteinhaus** [comment]
Thank god such a function exists. I quickly scanned `RenderPass` and the command encoder, but didn't know this was a thing.
All hail the superior cat knowledge.

**Comment by jazzfool** [comment]
Well these are all just staging helpers, the equivalent command is copy_buffer_to_buffer (from a mapped host visible buffer). Right now all these copy commands are being shoved at the start of the queue hence everything updates before rendering starts (leading to buffer overwrites and thus this bug)

**Comment by PSteinhaus** [comment]
Ah right, of course. Well I hope I'd have realized that we can do the `copy_buffer_to_buffer` mit mapped host buffers at some point, but I guess yesterday evening I was just like: "Is there any solution thats obvious to me to this, or do I need to ask someone who knows more about this than I do." And on `copy_buffer_to_buffer` I paused, but I wasn't sure then whether going that way would be considered a workaround or actually good practice, as I'm still not that familiar with wgpu.

**Comment by PSteinhaus** [comment]
Argh, this is slightly more complicated than I thought.
We can borrow the `CommandEncoder` mutably over `gfx.commands()` and the `StagingBelt` over `gfx.staging_belt()`, but we can't borrow both at once... So we could either make the staging belt public or provide a coupled getter mutably borrowing both at once.

**Comment by PSteinhaus** [comment]
Or perhaps its most elegant to write our own wrapper for `StagingBelt::write_buffer` instead of giving them access to the staging belt directly (which could also theoretically be misused) saving the user from having to get the command encoder, the staging belt, and then passing the command encoder in and writing our the buffer size.

We could write a function that does all that for them (deriving the necessary buffer size from the data given).
It would also make it slightly easier to use, as you can just pass in your data, instead of having to work with `BufferViewMut`.

**Comment by PSteinhaus** [comment]
Ok, none of this will solve our fundamental problem, as pointed out [here](https://github.com/ggez/ggez/pull/1133#discussion_r1020812546).

I agree that taking a look at whether we might get this solved using the growing buffer arena is a good idea.

**Comment by jazzfool** [comment]
Oh, yes, this is a side effect of WGPU sync model. Using a staging belt would only fix sync between passes. Indeed what could be done is basically creating a custom staging belt which uses a central growing buffer arena. This is already done locally (in the text renderer and internal canvas), but applying it globally to remove all the aliased buffer region writes should work.

**Comment by nobbele** [comment]
should be solved
