### ISSUE TITLE
Cannot open the framebuffer

### ISSUE THREAD

**Issue by omarandlorraine** [ggez/ggez#1141]
**Describe the bug**
Will not render directly to the framebuffer at /dev/fb0

**To Reproduce**
You just need a simple ggez application [this one](https://github.com/ggez/ggez/blob/master/docs/guides/HelloGgez.md) will do. Just go to the console (for example, by exiting X11, or by pressing Ctrl+Alt+F1 to get to the virtual TTY).

Type `cargo run`. See, an error: 

```
thread 'main' panicked at 'Failed to initialize any backend! Wayland status: NoCompositorListening X11 status: XOpenDisplayFailed', /home/<redacted>/.cargo/registery/src/github.com-1ecc6299db9ec823/winit-0.27.5/src/platfomr_impl/linux/mod.rs:719:9
```

**Expected behavior**
I expected ggez to run on the terminal as well. This would mean opening `/dev/fb0` or whatever and writing to it. It is important to note that exactly the same program runs just fine under Wayland or whatever. Only on the console does it fall over.

**Screenshots or pasted code**
If applicable, add screenshots etc to help explain your problem.

**Hardware and Software:**
 - ggez version: 0.8.1
 - OS: For example, Gentoo Linux
 - Graphics card: Intel Haswell-ULT
 - Graphics card drivers: this is fbcon driver, `i915drmfb`

**Comment by PSteinhaus** [comment]
Hmm... naive question (not much of a linux user myself to be painfully honest), but don't you like _need_ X11 for graphical applications? Based on this naive idea error thrown by wgpu makes perfect sense to me here.

**Comment by icefoxen** [comment]
@PSteinhaus You can write directly to the framebuffer on Linux if you really want to, it just involves talking to the kernel and GPU driver directly.  Usually this talking is what X11 or Wayland does for you.  Since we use winit and wgpu for drawing, these would have to support drawing to the framebuffer before we could.

Having a hard time seeing the use case for this.  It would also involve having to talk to raw input, making sure the framebuffer format matches what the game wants, dealing with multiple screens, and all the other fluff that X11/Wayland handles for you.  I could imagine wanting it for embedded-ish systems like handheld game consoles, but the ones I've seen will happily run X11/Wayland for you already.  So, I'm just kinda confused.

**Comment by omarandlorraine** [comment]
>Having a hard time seeing the use case for this [...]
> I could imagine wanting it for embedded-ish systems 

That's right; I am working on an alarm clock and fire alarm for the Deaf. I don't need much graphics acceleration for this application; just a framebuffer will do. I'm also very concerned about current draw (needs to run for 24 hours on quite a small battery), which is why I'm looking at trimming as much fat as possible from the environment. 

But I appreciate this use case is ... a little different, from what ggez is actually for, so if you guys don't want to support it I totally understand

**Comment by icefoxen** [comment]
Yeah that's a bit of an interesting use case!  Not sure if ggez is the right tool for that, the first thing that comes to mind for me is something like the [`embedded-graphics`](https://crates.io/crates/embedded-graphics) crate.  It doesn't look like it has built in support for Linux's fbdev though, maybe it can be wired together with [`linuxfb'](https://crates.io/crates/linuxfb) or the devs of either crate might have better info.  (Also, depending on your hardware, using the GPU may be more power-efficient than drawing with CPU.)
