### ISSUE TITLE
Support running inside a loop

### ISSUE THREAD

**Issue by isurakka** [ggez/ggez#117]
It would nice if the library could support running the game inside a loop in such a way where you initialize your stuff before the loop and then inside the loop you do updating and drawing. I find having to put everything inside the game state struct cumbersome.

Example:
```rust
// initialize everything

loop {
    // update
    // draw
}
```

**Comment by Manghi** [comment]
That's basically how it runs to be honest.

**Comment by icefoxen** [comment]
You can write your own event loop by diving into the underlying SDL a little, see event.rs for details.

It definitely would be nice to present a cleaner interface to be able to do that.

**Comment by icefoxen** [comment]
Now that I look into this I really can't figure out a better way of presenting this than what SDL2 does, so any code I'd write would really just be directly calling the SDL2 functions.  I can't just make a hook that returns the `EventPollIterator` because it depends on the `EventPump`, and I can't make the `EventPump` live in the `Context` because then you can't actually use the `Context` while processing events.  So really the only good way to deal with it is to, uh, do exactly what SDL2 does anyway: Make you call `sdl_context.event_pump()` followed by looping over `event_pump.poll_iter()`.

Suggestions are welcome but I don't reeeeally see any great solutions.  I've updated the `ggez::event` module documentation explaining the situation, at least.
