### ISSUE TITLE
Distributing large amounts of DLLS.

### ISSUE THREAD

**Issue by ateesdalejr** [ggez/ggez#142]
n00b question sorry...
I'm just starting out with ggez. And was wondering when I prepare my game for distribution is it possible to put all of my dlls in a directory different from the exe? To make rust search for them there instead of the current directory.

**Comment by Manghi** [comment]
You should be able to use a combination of `std::path::PathBuf` and `std::env::current_exe` to reference a sub-directory from the current executable's path. I did something like this in a non-github'd project (otherwise I'd link). Gist of it was something like...

```Rust
// Get PathBuf to current executable directory
// Pop off the executable name; now you have the cwd of your binary
// Push some other folder, says 'dlls/', onto that path
// Reference items from that path in your source
```
Also, I remember seeing somewhere that ggez can find resources in other directories which actually might be better (maybe `ggez::filesystem::Filesystem`?). Hope this answers your question.

**Comment by icefoxen** [comment]
You CAN put resources in other directories but I don't actually know if that affects dll's at all; I don't think it should.  I don't know how exactly Windows handles this sort of thing, since most of my domain knowledge is on Linux.  I will try to find out for you.

There's also the question of whether you want to actually load them explicitly with `dlopen` or such, or just link in libraries that use them such as `sdl2`.

**Comment by ateesdalejr** [comment]
nono... I mean the dlls that ggez uses SDL2 and so on.

**Comment by termhn** [comment]
SDL2 is the only dll that ggez requires... why do you want to put it in a different directory from the executable?

**Comment by ateesdalejr** [comment]
Dealing with clueless users is a bad thing sometimes. You never know if they'll delete something or not unless it's in a named directory e.g. "dlls"/"bin"

**Comment by icefoxen** [comment]
If your users delete random DLL's in random folders for no reason then they get what's coming to them.

**Comment by ateesdalejr** [comment]
Thanks for all of the help. :)
