### ISSUE TITLE
Image loading in debug build is slow

### ISSUE THREAD

**Issue by TatriX** [ggez/ggez#189]
I'm loading several quite big images with `Image::new()` with the following results:
```
cargo run --release
LOAD Duration { secs: 0, nanos: 346150935 }

cargo run
LOAD Duration { secs: 7, nanos: 663883538 }
```
Maybe I'm doing something wrong?

**Comment by icefoxen** [comment]
Rust in general is very slow in debug mode. This causes problems because theres currently no way to build ggez in debug mode but build all it's dependencies in release mode. So, the image crate ends up very slow.

https://github.com/ggez/ggez/issues/24 is an example of the same thing if you want benchmarks. I usually set debug mode to build with `opt-level=1` in my projects, which gets at least marginally acceptable performance.

We need to document this better, either in the examples or getting started docs or such.

**Comment by TatriX** [comment]
Cool, thanks. `opt-level=1` gives me 2 seconds, `opt-level=2` 0.3, which is fine.

**Comment by icefoxen** [comment]
Now documented in the FAQ.
