### ISSUE TITLE
Outlined Text

### ISSUE THREAD

**Issue by itmuckel** [ggez/ggez#211]
I'm currently developing a game in which I have to draw a lot of text. For that I use `ggez::graphics::Text`.
Unfortunately it is hard to read the text because of some background images. 

Is there a builtin way to draw text with black outlines?

Of course, I can draw the text twice, first black and a bit bigger, then in its final color a bit smaller to achieve this effect. But I thought I'll ask first, before implementing something myself, that's already there. ;-)

**Comment by icefoxen** [comment]
There isn't a built-in way; I don't think this is supported by rusttype.

However, I vaguely recall that some fonts DO have an "outlined" face, similar to "bold" or "italic", so that might be worth looking into.

**Comment by michaelbachner** [comment]
Yes, my first thought was getting an outlined font. But using it showed only the outlines and nothing inside. 

Wait... I have an idea. When you got the filled and the outlined version of a font, draw the filled version first in black or whatever color and then draw the outlines on top in white or whatever color. 

But this is very font specific and I'd like a general solution. There are far more non-outlined fonts.

**Comment by svenstaro** [comment]
This could be done using a shader or a post processing algorithm. Shouldn't be too bad to implement this naively. I'm just not sure we want they in ggez but I don't think it'll hurt.

**Comment by itmuckel** [comment]
I tried out two approaches.
1. add black font underneath with an offset (shadow):
![image](https://user-images.githubusercontent.com/18561536/33433083-8f979d7e-d5da-11e7-8114-dc7d2ed01ea2.png)
2. add four(!) black fonts underneath with an offset (one for each side):
![image](https://user-images.githubusercontent.com/18561536/33433448-e43399b8-d5db-11e7-8c8a-b22ce8bf06e0.png)

@svenstaro: If it's not so hard, then could you tell me how to do this? My game is not so graphically intense, so I have no problem drawing 5 texts, where one should be, but it feels so wrong. ;-)

**Comment by icefoxen** [comment]
Both techniques honestly look pretty good to me.  Drawing a text object 5 times should not be a huge problem since it's drawn via the GPU, but I agree that it feels wrong.  :-)

To disable smoothing when scaling text you want to use this function: https://docs.rs/ggez/0.3.4/ggez/graphics/struct.Text.html#method.set_filter , set the filter mode to `Nearest`.  Making the font renderer itself not try to do anti-aliasing is not something I know how to do though...

**Comment by termhn** [comment]
You probably want anti aliasing to be honest and just want to change the filter mode, but if you *really* want non-anti-aliased text, you could in theory draw to a separate Canvas with the samples set to 1 which would disable AA and then draw that canvas to the main one.

**Comment by OvermindDL1** [comment]
Why not just use SDF Fonts instead?  It is pretty trivial and *fast* to do effects like outlining and shadows and such with them.

**Comment by icefoxen** [comment]
@OvermindDL1 SDF fonts?

**Comment by OvermindDL1** [comment]
There are a few good pre-built ones you can google for, or you can generate them from a font file (I think freetype has support to output SDF fonts for example).

In essence an SDF font generated image generates the fonts on a mapping of 2 color channels (there are more advanced one that can use 3 or 4 color channels for more accuracy and effects) where each color represents the slope of the data there.  Then you just render the glyphs as normal except you replace the shader with a shader that reads those color values to determine whether to render or not (it is actually *very* simple).  In doing so by changing the bias between the colors and cutoffs and such you can do all kinds of effects trivially.  You can even encode the 'effect' you want to do on the glyph's vertices so you can trivially control the effect on a glyph-by-glyph basis so you can have something like `Hello` have each character have a different effect, like `H` with a shadow, e with an outline, the first l with both, the second l with a bigger outline, etc...

The big benefit of using SDF fonts is not just effect generation but in that the generated font texture does not need to contain all kinds of effects and you only need one texture generated for any amount of sizes of fonts so you can render the fonts at any size and they all look crisp and clear (if your SDF font texture is made well at least, otherwise you can occasionally get some odd angles but still work), and it does it all with no extra CPU computational cost, just a simple shader that is barely more complex than a stock font shader.

First google result is for libGDX, but it seems to demonstrate the basics of it pretty clearly:  https://github.com/libgdx/libgdx/wiki/Distance-field-fonts  :-)

**Comment by icefoxen** [comment]
Yeah fonts are a headache enough without trying to introduce a new type of font, and it looks like upstream isn't terribly interested in outlined fonts alas. Someone is free to dig into this more but I don't think I'm going to.

**Comment by IGBC** [comment]
Personally I agree with the idea of either drawing the font multiple times, or I would encourage the user to write a shader to render the edge of the font darker. 

Either way due to lack of activity I am closing this one.
