### ISSUE TITLE
Using multiple colors in a SpriteBatch

### ISSUE THREAD

**Issue by 17cupsofcoffee** [ggez/ggez#216]
Is is possible (or might it be possible in future) to set the drawing color on a per-sprite basis with the new sprite-batching functionality? I'm guessing not, since `DrawParam` doesn't take a `color` parameter, but there might be something I'm missing.

Context: I'm working on a console-style renderer for a roguelike, which involves me drawing individual characters from a greyscale spritesheet - that seems like low-hanging fruit to combine into a single draw call, but I'm using `graphics::set_color` to tint the characters at the minute, so I think I might be out of luck.

**Comment by icefoxen** [comment]
ggez sets colors basically in a shader global per draw call right now, and not per-vertex, which is honestly a little atypical.  I have mixed feelings about this style of drawing; it's mostly there 'cause it's inherited from LÖVE.

Adding a `color` field to `graphics::InstanceProperties` would be straightforward.  Then you'd want to remove the existing color field from `graphics::Globals`, and probably remove `graphics::set_color()` as well; having two "color" state variables seems like asking for trouble.  I don't *object* to such an API change (honestly I would prefer to have less implicit state rather than more) but am hesitant.  Looking at <https://love2d.org/wiki/SpriteBatch:setColor> suggests that they basically use two color state variables and it has not always been a good experience for them.  :-P

**Comment by 17cupsofcoffee** [comment]
Thanks for the explanation! It's not a massive issue for me if things stay as they are (my game is turn-based/not particularly flashy, so being slightly inefficient redrawing the map probably isn't the end of the world...), but I may have a go at writing a pull request if I get time, to see how well it'd work.

**Comment by icefoxen** [comment]
Hmmm, upon consideration, using two state variables may not be the *worst* thing ever... this is basically what we do for filter modes already.  There's a global default that everything that gets created uses, and then you can override it on a per-object basis.

That said, you generally don't want to change the filter mode for an image after creating said image, so.

The more I think about it the less I like the global color state, but I also *usually* want to go through life not forcing everyone to supply a color parameter to every draw call ever.  Perhaps we should have it set per object, since that's generally how graphics cards end up using it anyway in most API's?  That still doesn't work cleanly with sprite batches though, since they all draw from the same object.  So we'd need to be able to specify draw color per object *anyway*.

ugh.  The *easy and consistent* way is to force you to specify a color in `DrawParam`.  ...Perhaps we can have `DrawParam` contain an `Option<Color>` that defaults to `None`?  That doesn't sound too terrible honestly...

**Comment by 17cupsofcoffee** [comment]
Yeah, that doesn't sound like a bad idea, actually!

The main question there would be what happens when you pass `None` as the color. The obvious thing would be to just set it to white, but maybe `set_color` could stay/be renamed, and allow you to set the fallback? Then you'd still have the option of setting it globally if you wanted (which would be nice for `graphics::circle` prototyping/consistency with LOVE), but you'd have to opt in to it. Might still be a bit too global state-y though, I'm not sure.

**Comment by icefoxen** [comment]
Might have figured out a way to have our cake and eat it too, check out 9e7400f7654aeff6b9b4bff00f00717548beed96 (and test it out if you want, please!).

The way it behaves is that `set_color()` sets the default.  If `DrawParam.color` is `None` (the default), it will use whatever color has been defined by `set_color()`.

This makes me happy because it's a strict extension, preserves the old behavior when it's convenient, and gives you more powerful behavior when you want.  And should extend transparently to sprite batches.

**Comment by icefoxen** [comment]
Okay, doesn't quite work with sprite batches... YET.

**Comment by icefoxen** [comment]
Wait, it totally does!  Rock out.  See if you can break it, please!  \m/

**Comment by 17cupsofcoffee** [comment]
![Screenshot of demo program](https://user-images.githubusercontent.com/784533/34073625-46f5d230-e295-11e7-93b6-832d22c1270e.png)

All seems to work great - 4000 colored tiles are rendering at 200+ FPS in release mode :smile: My implementation is fairly janky/inefficient too, so the fact that it's already running this well is very encouraging.

Only issues I ran into were:
* If I pass `None` as the color of one of my batched draws, I get a panic - it looks like the implementation of `Drawable` for `SpriteBatch` doesn't call `update_instance_properties`, so the default color never gets copied across.
* Spritebatching is super slow in debug mode, for similar reasons to those mentioned in #131 - had a look at my profiler to make sure it wasn't anything stupid I was doing, but all the cycles were being spent in nalgebra matrix conversions. Oh well, will just have to go with `opt-level=1`.

**Comment by icefoxen** [comment]
Awesome!

Fixed the crash, I believe, in b208c6c8b22e48ea2a7b4d7fe02bd88454330640 .  Along with making colors cascade down to the contents of the sprite batch... so if you specify a color with `graphics::set_color()`, the spritebatch will use that, unless you override it in the spritebatch's `DrawParams`, unless you override *that* in the *sprite's* `DrawParams` when adding the sprite.  Whew!

This may, alas, have a minor impact on the performance of sprite batches...  Please let me know if you have any problems!

**Comment by icefoxen** [comment]
Closing this, since it doesn't seem to bother anyone.  :-P
