### ISSUE TITLE
black screen with latest nightly Rust

### ISSUE THREAD

**Issue by AaronM04** [ggez/ggez#219]
Hi, @Manghi and I have a game using ggez 0.2.2. I noticed on Linux that after upgrading to the latest nightly Rust, I get a black screen for the main screen in our game. I confirmed that it works in the last stable Rust (1.22.1, released 2017-11-22). The black screen problem occurs on the 2017-12-01 and 2017-12-06 nightly releases.

Have you seen anything like this or heard about problems like this?

**Comment by icefoxen** [comment]
Haven't seen this before, no.  But I don't usually test on nightly.  It tends to, uh, break randomly.

ggez 0.2.2 is pretty darn old too.  Didn't think anyone was still using it!

**Comment by itmuckel** [comment]
I use nightly all the time and never had such problems. @AaronM04 have you adapted your code to the newest version? Maybe you use some deprecated functionality that hasn't been deleted from the sources yet? Just a blind guess. We need more information and (best case) the source to verify/cross check it. ;-)

**Comment by Manghi** [comment]
We're still on 0.2.2 because when we switched over to 0.3, we experience a huge slowdown for what we were drawing, thousands of rectangles! I think this was discussed in #127 a few months ago, so we decided to stick with 0.2.2 now.

We just tested nightly (12/14) under 0.2 and the same issue appears. We narrowed it down to filled rectangles; line rectangles (no fill) do not have any issue when drawing them. 

[Here's a working example of this issue in Astroblasto](https://gist.github.com/AaronM04/c8297e0905be40afafd94c41a5c0227e#file-astroblasto_line595-rs-L595) (btw very fun game 😄). This needs to be run using your 0.2 branch of ggez.

The last stable verified as working is released on (11/22).

**Comment by termhn** [comment]
If you use the new sprite batching on master (slated for 0.4) you should see a large increase in performance drawing thousands of rectangles over any previous version.

**Comment by Manghi** [comment]
I went that route ~2 weeks ago but ran into the mesa driver issue, but I'll give it another shot since I *think* that was recently fixed on master. Regardless, I think is a pretty interesting issue to see what is causing this behavior.

**Comment by Manghi** [comment]
Finally got around to trying out sprite batching through `0.4-rc2` and it works beautifully on both nightly and stable! So beautifully that we might have to limit the FPS since its drawing much quicker than before haha. Something else that will need investigation. 

Quick shout out to @icefoxen for adding color support to SB a few days ago in `0.4-rc2`. What a terrific job! 

For those of you who are curious, to accomplish the thousands of rectangle drawings, I created an image of a 1-by-1 pixel via 
```Rust
graphics::Image::solid
``` 
and colored it white. That enabled it to be scaled to any size, and color-able.

Ticket can be closed, though I would update the abstract to reflect this occurs on ggez version 0.2 only.

**Comment by icefoxen** [comment]
Thank @17cupsofcoffee , it was their idea!  I just figured out how to smooth over the rough edges between it and the existing color stuff.

FPS limitation with 0.4 is demonstrated in the current astroblasto example.
