### ISSUE TITLE
Make a better website

### ISSUE THREAD

**Issue by svenstaro** [ggez/ggez#23]
Since love2d is our role model, why not make design our site to look a little bit like [them](http://love2d.org/)? Certainly we can do better than the default Github generated site.

**Comment by icefoxen** [comment]
Oh snap, we need screenshots!

**Comment by onelson** [comment]
Maybe think about what you'd like to build this with and I can sketch some stuff out. Assuming you're looking for a static site, there are many options available.

Personally, I use https://jekyllrb.com/ for my personal blog but there's a rust port(ish) https://github.com/cobalt-org/cobalt.rs which might work if you literally want everything in your life to run through `cargo`.

Jekyll/cobalt don't lend themselves to not-a-blog as much as http://grow.io/ and https://github.com/gatsbyjs/gatsby which seem super flexible. Might be a good way to go since they are more "site builder" type projects.

I know @svenstaro mentioned liking the look/feel of https://rocket.rs/ and I peeked at the markup, but there weren't any clues as to which system was used to generate it (that I recognized at any rate).

If language is a factor, here's the tl;dr:

* Jekyll: Ruby
* Cobalt: Rust
* Grow: Python
* Gatsby: Node

Maybe that rules something out.

**Comment by svenstaro** [comment]
I believe using cobalt would be most in spirit with this endeavor if you think that's workable.

**Comment by onelson** [comment]
I'll take a look at it, but it's probably towards the bottom of my picks in
terms of lowering friction (which is ultra important for a project like
this). Cobalt and Jekyll with both likely require the use of other build
tools for stylesheet processing (for example). Grow and Gatsby look to take
care of this as a part of their builds.

Still, I'll give it a shake and see if I can work it.

Owen Nelson

**Comment by svenstaro** [comment]
If Cobalt turns out to be too icky then I'd be all for Grow since I know Python very well.

**Comment by icefoxen** [comment]
Good luck, either way.  My only opinion on tooling is "not javascript", so.  Cobalt and Grow both look fine.

**Comment by onelson** [comment]
I hear you loud and clear.

**Comment by icefoxen** [comment]
Hmmm, http://gtk-rs.org/ has a nice website.

**Comment by icefoxen** [comment]
Honestly?  Our website is pretty darn cool now.  Can we close this?

**Comment by onelson** [comment]
I don't know...

**Comment by svenstaro** [comment]
I have some plans for working on it. The site is certainly not where I want to see it in the end.

**Comment by icefoxen** [comment]
All right svenstaro, I'll leave this one in your court.  :-)

**Comment by icefoxen** [comment]
Just a reminder for us in the future: Both the install instructions and projects list in `docs/` would be useful to migrate over to the website once we have a place for them.

**Comment by icefoxen** [comment]
Github pages now supports HTTPS: https://blog.github.com/2018-05-01-github-pages-custom-domains-https/

Making that work would be nice.

**Comment by icefoxen** [comment]
Turns out that for small stuff it's honestly easiest to just edit the HTML directly instead of trying to get the static site generator to the right version and remember how it works.
