### ISSUE TITLE
Adding variable width bitmap fonts

### ISSUE THREAD

**Issue by makoConstruct** [ggez/ggez#270]
I intend to make some changes/additions to bitmap fonts. There's a small backwards-incompatability so it might have to be another font mode alongside ttfs and bitmaps... my taste would have us deprecate the old one, but we couldn't just replace it.

The new mode will support variable-width fonts. It will scan through the bitmap, reading fully transparent lines as glyph boundaries, finding the start and end of each glyph and storing them in the `glyphs` map. I'll have to write more complex flow calculation code for sizing, presumably, but I've done this before.

The little problem: This will not generally be able to detect a space character, the space character will just read to it as nothing. I'll just have there be a `space_width` parameter. So, to convert to this new method, users would have to

* remove the space char from their `glyphs:&str`

* add a `space_width:usize` value

Can I get a green light?

Help though; what is [this](https://github.com/ggez/ggez/blob/636b070639f13411fd705957054271c39d64c39d/src/graphics/text.rs#L90) `image`? The imports just say `use image;` and.. I don't know what that would mean. I could just assume it's shaped like a a row-major vector of `Color`s and start writing code but it would be good to have that confirmed.

**Comment by icefoxen** [comment]
Fully transparent lines as glyph boundaries is not necessarily what you want; you may want some glyphs to have some space around them more than a single line.  For a variable-width font to work really well you'd probably also want to have at least some notion of variable height, so you'd need to specify at least the line spacing and the ascender-descender sizes as well...  At this point it feels like you're going to rapidly end up re-inventing Truetype.

It's definitely a useful idea, and I certainly encourage you to mess around and make cool stuff.  But given that I haven't even checked to make sure the existing bitmap font code works in a year, I'm not super excited about having more complicated bitmap font code to maintain.  ...however, it occurs to me that the existing bitmap font code could (and probably should) be rewritten to use a `SpriteBatch`, instead of its current approach of blitting everything to a buffer.  Doing something similar with ttf fonts is basically the goal of #132 .  So it might be time to consider a serious font rewrite anyway.

Rock out and make a prototype.  I suggest finding/creating some sort of font metrics structure that stores glyph locations and using `SpriteBatch` for drawing.  This might get into sharing issues with `SpriteBatch` but those are probably worth solving anyway.

**Comment by makoConstruct** [comment]
>Fully transparent lines as glyph boundaries is not necessarily what you want; you may want some glyphs to have some space around them more than a single line.

When? I mean.. *I* don't. I can't imagine wanting that. It might make sense to provide a general `letter_spacing` variable, if that's what you mean?

>For a variable-width font to work really well you'd probably also want to have at least some notion of variable height

Why? It seems fine to me to just treat every glyph as having the same height. High variation in vertical height isn't exactly a good feature for a font to have.

You neglected to answer the question about `image`.

I really think this is a good optimum of ease and flexibility. Makes it very easy for a dev to draw their own fonts. I'll probably go ahead and do it. I accidentally did half of it yesterday. It's not going to be too complex.

**Comment by icefoxen** [comment]
If you have a variable-width font, you don't always want the same width between characters for kerning and such.  And variable height would let you use a sprite packer or such to pack letters closer together.  I confess, I may be over thinking this.

Sorry, I got distracted from your question about `image` and forgot about it; it's this crate: https://crates.io/crates/image/ .

Go ahead, I'll be happy to play with what you produce.  I didn't mean to sound like I'm brushing you off.

**Comment by icefoxen** [comment]
@makoConstruct I feel a bit bad because I *just now* realized you're the same person who opened #268 , so I basically told you "use bitmap fonts for pixel-perfect drawing" followed immediately by "use TTF for variable-sized drawing".  :-/  That was not really the message I wanted to give.

Unfortunately those are the two poles we have right now, without a whole lot of wiggle room in between.  Improving this situation is definitely desirable.  Unfortunately I'm frankly not certain *how* to do this really well right now.  It would be easy to add a method that lets you specify an actual pixel size to rusttype rather than a point size, now that I look at it, but everything I know about font rendering says "for the love of Eris don't try to force it to a particular pixel size, everything should be relative and flow smoothly".  But when you're making games and UI's instead of writing documents then that's not always possible.  Everything I know about making games ALSO says "for the love of Eris don't try to force it to a particular pixel size", but usually that's not entirely practical, especially for 2D pixel-y stuff, and the best you can do is allow a set of particular pixel sizes that work well...

Maybe everything I know is wrong.  Text rendering deserves a bit more love than it's gotten lately anyway, so this is something we should think harder about.

**Comment by makoConstruct** [comment]
It did turn out that bitmap fonts was the sensible way of doing what I wanted, it was just a bit hard to convince http://www.pentacom.jp/pentacom/bitfontmaker2/ to give me a bitmap instead of a ttf (I had to hack at the preview canvas to make it wider then edit the result in gimp x__x)

My experience is that most people wont notice if you straight up don't have kerning. A font shaping engine doesn't have to be all that sophisticated to be useful for games.

I think the thing I'm gonna do will always be a common use case. If you wanna draw your own pixel fonts for pixel games you're really not going to want more sophistication than this.

**Comment by icefoxen** [comment]
Thanks, I look forward to seeing your results.  Still undecided whether it's something we would want to pull into ggez itself or something that should be kept as an external library.  This might become something that becomes supported by upstream libraries anyway, see https://github.com/alexheretic/gfx-glyph/issues/17 .

**Comment by makoConstruct** [comment]
It's not ready to be merged, I haven't even tried it out yet, but if you want to see the algorithm, this is essentially it https://github.com/makoConstruct/ggez/blob/master/src/graphics/text.rs#L509

**Comment by makoConstruct** [comment]
Oh, I meant to ask, why are the font variants enums? Why not traits? There doesn't seem to be an advantage there if users aren't often dynamically distinguishing the variants, it just adds runtime discrimination overhead and jams the code for different implementations into the same functions.

Current changes:
* removed some unnecessary parens in context.rs that were triggering warnings
* replaced a use of str.len

**Comment by makoConstruct** [comment]
Oh, I meant to ask, why are the font variants enums? Why not traits? There doesn't seem to be an advantage there if users aren't often dynamically distinguishing the variants, it just adds runtime discrimination overhead and jams the code for different implementations into the same functions.

Current changes:

* removed some unnecessary parens in context.rs that were triggering warnings
* replaced a use of `str.len()` in bitmap font rendering with `str.chars().count()`. `str.len()` would have overshot the actual char count sometimes because utf8, for instance, you would have ended up with textures that were at least twice as long as they needed to be for japanese text.
* changed an `ok_or` to `ok_or_else`. ok_or would have been allocating the error for every single character then throwing it away when it wasn't used. or_else methods only make the error when it's needed.
* typed out dynamic text rendering

**Comment by icefoxen** [comment]
It was just easier to make the font variants members of an enum, and had no particular cost either.  I think at the time my thought was that it makes it slightly easier to read what's going on in a function for rust newbies because they don't need to deal with generics or trait objects.

Code looks very nice in general, though I do encourage you to use a `SpriteBatch` rather than `blit()` to put together your `Text` object.

**Comment by icefoxen** [comment]
Okay, I'm in a less curmudgeonly mood now and I've had time to think about this and figure out what is in the future of various other libraries like `gfx_glyph`.  You're right, adding variable-width bitmap fonts to ggez would be really easy, and since the bitmap font stuff needs to be improved anyway the incremental cost is basically zero.  It would be *nice* if someone wanted to tackle [this proposal](https://github.com/alexheretic/gfx-glyph/issues/17#issuecomment-363135155), but I'm certainly not doing it any time soon, so I'm not going to wait for someone else to.  :-P

I do think that it would be nice to have bitmap font handling separated out into its own crate that ggez could depend on, but that's true of a couple other parts of ggez anyway (the filesystem stuff mainly), so if you don't want to do that then it's fine.

So, now that I'm looking at your code again, and more seriously:

 * `BitmapFont` can be ripped out and replaced with `DynamicBitmapFont` entirely, just add a constructor that builds a `DynamicBitmapFont` with the same width for every glyph
 * If you do the spritebatch approach, feel free to just clone the font's `Image` so that the `Text`'s `SpriteBatch` can own it; an `Image` is actually an `Arc`'d handle to a GPU texture, so needs no extra memory allocation to clone.

**Comment by makoConstruct** [comment]
So, do you mind if I rework it to traits? It would have been entirely possible for dynamic width font to be an external crate if they were traits :p (although I don't think it should be an external crate)

Hmm I'll need to rework the way it looks at spaces superceding the old bitmap behaviour seems possible

**Comment by icefoxen** [comment]
Go right ahead, though I'd prefer changing the public API as little as possible.  It'd be cool if this could get merged without a major version bump.  If not though, well, that's fine, it'll just wait a little longer before it gets released officially.

**Comment by makoConstruct** [comment]
>though I'd prefer changing the public API as little as possible
=c
[Definitely wants to do it.]

There _is_ a bit of difficulty with the way it handles spaces. I could probably replicate the old behaviour with spaces, but it would be some pretty inelegant code for a feature that probably no one is using, that probably no one _should_ use.

The new behavior, if that's okay: Spaces are always rendered as empty. No space char needs to be provided by the font but things don't break if one is.

Old behavior: You can have a custom space char that isn't just empty space. You can have a space char that renders as a flower. I don't see why a person would want to do that. In the new code, flowers instead of spaces could be implemented by just mapping the spaces in your strs to explicit flower chars before rendering.

**Comment by makoConstruct** [comment]
Wait, argh! No. This is easy.

**Comment by makoConstruct** [comment]
Got around to trying it out in my game. Removed The Bug. Ready to merge. Should I call the new Font variant just BitmapFont? Seeing as it's the only Bitmap Font variant now?

**Comment by icefoxen** [comment]
Sure, that works.

**Comment by icefoxen** [comment]
#290 is merged and appears to work just fine, so, closing this.
