### ISSUE TITLE
Wrong mouse click position with FullscreenType::Desktop

### ISSUE THREAD

**Issue by itmuckel** [ggez/ggez#273]
On my PC I use the resolution 1920x1080.
My game uses the resolution 1680x1050.

When I click on something in the game it feels like the click position is translated falsely. When I click in the top left corner the click position and the game action (showing a cross where I clicked) are at the exact same position. But the greater the distance from the top left corner the greater the distance will be between where I clicked and what the game shows.

Anyone else experienced this?

When the game and PC resolution are the same, the click position is right everywhere.

This bug occurs only for `FullscreenType::Desktop`. With `FullscreenType::True` the behavior is right for every game resolution.

But I'd still like to use `FullscreenType::Desktop` as the game starts faster. :smile:

I use ggez 0.4 on Windows 10 with rust nightly 1.25.

**Comment by icefoxen** [comment]
Thank you for the big report! This one is interesting. What platform/os are you on?

**Comment by icefoxen** [comment]
Oh, win 10, you said. My bad.

**Comment by itmuckel** [comment]
Theoretically this cannot work without scaling the final picture.
Dimensions of window: 1680x1050
Dimensions of desktop: 1920x1080
When I start the game I see no scaling applied. The game fills out my whole screen. With these dimensions I should at least see black borders (like in a movie). Hmmmmmm. I hope you understand what I mean. 😄

**Comment by icefoxen** [comment]
Yeah, looking at this more, setting screen sizes and fullscreen/non-fullscreen is unfortunately somewhat flaky.  Like, calling `graphics::set_fullscreen()` appears to not properly preserve the dimensions of the window, and changing the resolution nukes the fullscreen state for some reason.  So I need to figure out where it's going wrong and make sure everything stays in sync.  :-(

I don't even know why `set_fullscreen()` and `is_fullscreen()` take and return a `bool` instead of a `conf::FullscreenType`...

**Comment by icefoxen** [comment]
Sorry for the delay checking up on this, friend.

On Linux at least, when you ask for `FullscreenType::Windowed` in the `Conf` (ie not setting it at runtime) then you get a window that is the resolution of whatever the desktop is.  It is scaled up for you to fill the whole screen (changing the aspect ratio if necessary, instead of letterboxing) but, for example, the locations of the mouse clicks will reflect the full size of the screen.

Easy fix, as far as I can tell, would be to have all your mouse coordinates be relative to the true size of the window.  `graphics::screen_size()` seems to return the true window size is in either fullscreen mode.

I will check this on Win10 later tonight.

**Comment by icefoxen** [comment]
Reproduced on windows.  Has the same behavior; when you ask for `FullscreenType::Desktop` it gives you a window the size of the desktop, whatever resolution the desktop is.  When you ask for `FullscreenType::True` then it sets the screen resolution to what you request, and gives you full screen access.

I can certainly see that this is surprising behavior but I'm not really sure I can call it a bug; it's giving you exactly what you ask for.

Feel free to re-open this if you have a better way of handling it.
