### ISSUE TITLE
Link in API Docs is Broken

### ISSUE THREAD

**Issue by CaptainKraft** [ggez/ggez#291]
Link to `Duration` is broken.

I found it when looking into `get_delta()` and haven't seen any other broken links yet.

**Comment by icefoxen** [comment]
That's interesting; it links to <https://doc.rust-lang.org/nightly/std/time/duration/struct.Duration.html> which does not exist.  <https://doc.rust-lang.org/stable/std/time/duration/struct.Duration.html> (stable instead of nightly) does exist, but the official rust docs are just at <https://doc.rust-lang.org/std/time/struct.Duration.html> .

It appears that docs.rs builds with the nightly version of the compiler, which seems a strange decision to me since it often breaks, but no helping that part.  This also means it links to the nightly docs, it would seem.  

Aha, there the docs do exist at <https://doc.rust-lang.org/nightly/std/time/struct.Duration.html> , so no `duration` subdirectory.  So the question really becomes, "why does docs.rs aim at the wrong directory?"  I suspect rustdoc has changed out from under it and it hasn't caught up.

**Comment by icefoxen** [comment]
This appears to be fixed now!  See upstream issue.
