### ISSUE TITLE
Background color clear in canvases has effect on rendered stuff even if alpha is zero

### ISSUE THREAD

**Issue by LaylConway** [ggez/ggez#301]
My best guess is that alpha isn't being pre-multiplied here, resulting in wacky blending.
This is what it looks like when the background color is set to `(255, 255, 255, 0)` before clear
![](https://i.imgur.com/km4Ghtx.png)
This is what it looks like when the background color is set to `(0, 0, 0, 0)` before clear
![](https://i.imgur.com/C3UYGjp.png)

**Comment by icefoxen** [comment]
This is interesting, possibly a flaw in how colors are set for canvases or combined together among canvases.  That's a bit of a hairy use case.

**Comment by LaylConway** [comment]
This seems to be causing some serious issues for font rendering.

The top line is rendered on a transparent canvas, then that canvas is rendered on a white background.

The bottom line instead has a white box first rendered behind it.

![example_2018-03-10_03-41-49](https://user-images.githubusercontent.com/3094382/37237575-396f7514-2415-11e8-9ab3-fe49b1feaa64.png)

**Comment by LaylConway** [comment]
Looking further into it, this weird blending seems to happen as soon as text renders onto a canvas with an alpha background

**Comment by icefoxen** [comment]
Like #253, can't reproduce on my laptop.  Need to try on other platforms.

@LaylConway If you're still around, what OS and GPU are you using?

**Comment by LaylConway** [comment]
Windows 10 64-bit
NVIDIA GeForce GTX 970
Current driver version is 390.77 though this has persisted across driver versions

**Comment by icefoxen** [comment]
Thanks.  Can you post a minimal example program so I make sure I'm testing the right thing?

**Comment by icefoxen** [comment]
Ok, using the linked test program, setting one color to `(0,0,0,0)` and the other to `(255,255,255,0)` definitely makes a difference.  The background flips from black to white, on any platform.  Not sure what I was doing before that didn't make it show up.  It should stay basically undefined either way since the alpha is always 0.

I'm very sleepy so I'm going to have to attack this when I am more awake, but as with #253, commit https://github.com/ggez/ggez/commit/35a41e7f00030aabd7f3433dee943e6df2732da6 seems suspicious since it doesn't really set the source alpha.  But that should only matter for the text, not the whole canvas.  Check and make sure blending is set correctly maybe?

**Comment by icefoxen** [comment]
Ok my test program was hecked up.  Fixing it reproduced the error:


![image](https://user-images.githubusercontent.com/1335133/40585304-2bc3a038-617e-11e8-85b2-8aaf3545298b.png)

**Comment by icefoxen** [comment]
Okay, observations:

 * Setting the alpha of the text to 1 still makes those weird fringes appear
 * This happens with any image, not just text

![image](https://user-images.githubusercontent.com/1335133/40585796-7a80376a-6186-11e8-9270-df85f2b8b951.png)

Happens even if you don't set the color

![image](https://user-images.githubusercontent.com/1335133/40585808-b0deccae-6186-11e8-87af-595cc20a963c.png)

You have to set the background to a color that is not white or black for it to show up, which is why we've never seen this before.

Turning off sRGB conversion in shader stuff doesn't seem to make a difference.

The weird raster-y little chunk-y color fringes don't seem to change size with multisampling level.

![image](https://user-images.githubusercontent.com/1335133/40585996-e55214da-6188-11e8-8344-cfa6ea6b3dbc.png)

**Comment by icefoxen** [comment]
Okay there's THREE places the color matters:

 * Screen background color
 * Canvas background color
 * Color with which the canvas is drawn on the screen

Still checking whether the math adds up.

**Comment by icefoxen** [comment]
Like #253, make a *good repro*, then test it on all GPU's.

**Comment by hecrj** [comment]
I just had this issue when trying to programmatically create a sprite atlas.

I was able to fix it by calling `graphics::set_blend_mode(ctx, graphics::BlendMode::Replace)` before rendering to the canvas.

**Comment by PSteinhaus** [comment]
> I was able to fix it by calling `graphics::set_blend_mode(ctx, graphics::BlendMode::Replace)` before rendering to the canvas.

This (or using `BlendMode::Replace`) is indeed a workaround for this. But now that ggez also has a "Premultiplied" blend mode there's actually a more proper solution for this (see #694).

The issue here is how "classic" alpha blending works, which is the default in ggez.
Using this default blend mode color channels get multiplied with their alpha channel (i.e. the source alpha) and then added to the color of the target (here a transparent black/white canvas, so either white (=1) or black (=0)) multiplied with (1 - source alpha).
This of course leads to changed colors. So when you then render that canvas onto the screen using the default blend mode the colors are too dark or too light.

To fix this you need to use `BlendMode::Premultiplied` when rendering the canvas onto the screen, so that the premutliplication step doesn't happen again. Then (given that you only drew to the canvas using `BlendMode::Alpha` (or `BlendMode::Premultiplied` with premultiplied images, that is, contents of another canvas, or images that were already premultiplied using some helper function or other application)) you should get exactly the same result as if you rendered everything to the screen directly using `BlendMode::Alpha`.
