### ISSUE TITLE
README: List supported and planned platforms?

### ISSUE THREAD

**Issue by ozkriff** [ggez/ggez#323]
This information is crucial for potential users skimming through the readme but they need to discover `docs/BuildingForEveryPlatform.md` document to see it.

I propose to add a list of supported (and planned) platforms near "Features" section.

Or at least add a link to `docs/BuildingForEveryPlatform.md` file to the readme.

**Comment by ozkriff** [comment]
> ## Platforms
>
> - Supported: Windows, Linux, macOS
> - Not officially supported yet: Android, iOS, Web/WASM/Emscripten

@icefoxen Something like this?

**Comment by icefoxen** [comment]
Done!

**Comment by ozkriff** [comment]
Who-hoo!

btw, why have you pushed directly to master branch? I thought that all new commits go to `devel` branch.

**Comment by icefoxen** [comment]
Because in this case it's something that needs to be in the master branch, so people can see it when they come to the github page.

Important fixes to the readme or examples or such need to be visible to people without them looking at the devel branch, or else people just re-report the same errors.  I could push to devel and then cherry-pick the commits into master, but it results in the exact same thing.

Technically maybe it should be a new release, but changes to the readme and examples are things that people generally *don't* see when using ggez through cargo, so...  :man_shrugging: 

I'm bad at strict procedures, I guess.
