### ISSUE TITLE
Z-axis draw param

### ISSUE THREAD

**Issue by dettalant** [ggez/ggez#366]
Currently, ggez can't use a z-axis draw param. because ggez not have depth test implement.

Although z-axis param is not essential for 2D game develop, very useful when developer make complex draw order mechanism.

To be honest, I'm want this...

**Comment by icefoxen** [comment]
Right now the only way to control draw order is, well, to draw things in a different order.  You can implement your own 3D drawing using the `gfx` bindings, but it's a bit of extra work.

I don't especially want this, but apparently there's demand for it.  Anyone else have opinions?

**Comment by Ratysz** [comment]
I'm a bit on the fence. I can see how depth testing could be useful, but I
also see easy solutions on how to do without, as far as 2D is concerned.

Still, if it's possible to support this without any API changes (ie,
strictly optional), then why not?

**Comment by OvermindDL1** [comment]
Using pure-order-based rendering means it will *always* be less efficient then it could be otherwise since batching of identical render states can then not be performed unless they are absolutely adjacent in order.

**Comment by icefoxen** [comment]
@OvermindDL1 That's true, but it's basically the problem that spritebatches are designed to solve.

**Comment by OvermindDL1** [comment]
> That's true, but it's basically the problem that spritebatches are designed to solve.

> Well, you'd need all items in a sprite batch to be on equivalent z-layers
> if you don't have depth testing I think is the idea

Spritebatches as they are are ordering-based renders, meaning all of the type have to be rendered at the same time if you want to batch, meaning they all have to be on the same layer.  Depth testing makes it so they don't all have to be on the same layer.

**Comment by icefoxen** [comment]
After thinking about it a little more, I don't like the idea of making ggez do explicit Z coordinates.  That will just bring a giant morass of OTHER features until we end up with a 3D renderer, not a 2D one.

BUT!

Since internally each `Drawable` gets its own full `Matrix4` transform, if we make SOME way to expose that, then it will be possible for a user to set that up however they want, including Z coordinates.  So, any objections for closing this in favor of #367 ?
