### ISSUE TITLE
Rewrite renderer to use gfx-hal

### ISSUE THREAD

**Issue by termhn** [ggez/ggez#418]
This is something I'm interested in working on. Possible resources to look at:

* https://github.com/omni-viral/gfx-render
* https://github.com/omni-viral/gfx-memory
* https://github.com/omni-viral/gfx-chain
* https://github.com/omni-viral/gfx-mesh
* https://github.com/omni-viral/gfx-texture

**Comment by icefoxen** [comment]
My vague internal roadmap has this as the major change for 0.6, so... Heck yeah!

A little torn between using raw gfx-ll vs. getting gfx-render in a usable state. The latter is probably the way to go, but...

**Comment by termhn** [comment]
I think @omni-viral has been working hard on getting gfx-render (and his xfg crate that depends on it) to a good state since it will be used in Amethyst's new renderer, so I figure it will probably be a good choice.

**Comment by icefoxen** [comment]
I confess I haven't looked too hard at `gfx-render` since it was brand new, so I don't know its current status.  Collaborating with Amethyst people is always cool though!

**Comment by omni-viral** [comment]
I would like any feedback 😄

**Comment by omni-viral** [comment]
Note that gfx guys introduce breaking changes frequently

**Comment by omni-viral** [comment]
https://github.com/gfx-rs/gfx/issues/2206

**Comment by termhn** [comment]
With above mentioned issue in mind and based on the fact that many of the gfx influencers seem to agree (as do I) taking hal in a new direction is a good idea, I think it may be best to hold off on his for now and then either write directly on top of the "new-hal" crate, whatever that ends up being, or use Ash/Vulkano (would probably lean towards Vulkano for this) if they end up leveraging it underneath.

**Comment by icefoxen** [comment]
I'm frankly sort of sick of waiting for gfx-hal, so that might be fun.

**Comment by bsvercl** [comment]
@termhn I've been working on creating a Vulkano renderer for GGEZ. I have things like drawing meshes and drawing images done. It's not a public repository yet, though.

**Comment by termhn** [comment]
@bsvercl Nice! Are you planning on putting it on a public repo soon?

**Comment by bsvercl** [comment]
Yeah I'll probably put that up tonight! There's still a couple things I don't understand about Vulkano, but I'm still learning. :)

**Comment by omni-viral** [comment]
One thing I didn't get about vulkano is how it handles resource synchronization.

**Comment by bsvercl** [comment]
@omni-viral The docs [here](https://docs.rs/vulkano/0.9.0/vulkano/sync/index.html) should explain somewhat how it handles synchronization. I still don't fully understand futures myself.

**Comment by bsvercl** [comment]
Things didn't work out how I had hoped. It ended up being much different than my standalone prototype that functions very well. I'm hoping someone more familiar with the ggez codebase could help me sort some things out. 

Be warned, this is **very** ugly code, and not documented at all. [Here](https://github.com/bsvercl/ggez/tree/vulkano) is the repository.

**Comment by icefoxen** [comment]
Well, the ggez codebase is kinda undergoing a few significant shifts at the moment anyway, so that isn't necessarily going to make things easier.  My own knowledge of vulkan is currently at the level of "managed to draw a triangle, once", so that doesn't help either.  But the basic structures of ggez's graphics stuff, apart from lots and lots of windowing, input and setup stuff, are basically a rectangle mesh used to draw sprites, an instance buffer of sprite properties (transform, color, source rectangle) used to draw sprite batches (and drawing `Image` draws a single item from that instance buffer), and the gfx-rs structures of `Factory` for creating resources and `Encoder` for queueing commands into a command buffer.  The actual drawing of stuff is extremely simple, it's all the fru-fru around it that's complicated, and that's the stuff that ggez is intended to handle so game developers don't have to.

Sticky things that I don't know how to deal with would include: Memory management, semaphores (though ggez's API is basically synchronous so handling these The Simple And Dumb Way is probably fine), and swapchains.  I gotta admit I was intending to eventually lean quite hard on some higher-level helper libraries like `gfx-chain` and `gfx-memory`.

**Comment by omni-viral** [comment]
@icefoxen if ggez workflow doesn't require to have multiple renderpasses then you'd only need to synchronize with presentation engine, which is ez. You didn't mentioned pipeline barriers, I consder them to be hardest part.
Vulkano uses futures to synchronize execution, I guess it tracks resource usage and synchronizes internally so vulkano is order of magnitude simplier to use than raw vulkan (or hal).

**Comment by bsvercl** [comment]
I've made a lot of improvements since the last time I commented here. Just a couple things missing now.

**Comment by termhn** [comment]
Okay so I'm now experienced enough that I feel I could definitely do this, however I also think it's not going to be beneficial enough for us yet to outweigh the cons. For example, the GL backend is not ready for use at all yet, so we'd be losing that which I think is very important for something like ggez.

**Comment by icefoxen** [comment]
We just need to write an OpenGL backend for gfx-hal then!  :grin:

**Comment by termhn** [comment]
I think you might be right... another project I'm working on also wants to do this, so I've decided to try to shore up the gl backend where I can at least to the point it works for what they and we need it to.

**Comment by mtak-** [comment]
Am I correct in assuming the status is that `gfx-hal` support is planned, but no substantial "public" work is available towards moving `ggez` in this direction?

If `gfx-hal` support lands will `ggez` be backend independent? It'd be great to have `ggez` running on metal.

I'm assuming this is still more than a month away from happening. Is that correct?

Thanks for all the hard work!

**Comment by icefoxen** [comment]
@mtak- You are correct on all these counts.

**Comment by erlend-sh** [comment]
Rendy is out now, which supersedes all of the libraries mentioned above.
https://www.reddit.com/r/rust/comments/apeq8v/rendy_is_released/

**Comment by icefoxen** [comment]
Update for the record, to summarize various conversations with various people: rendy is basically the successor to gfx-render.  wgpu is also worth considering but is currently very unstable.  gfx-hal is quite stable and functional but not perfect, and OpenGL support for it is currently very much WIP.

**Comment by omni-viral** [comment]
Since both rendy and wgpu are gfx-hal based, they both lack OpenGL support until gfx-hal will provide in more or less consistent state.
Although rendy was not supposed to be gfx-render successor, there is nothing else to fill that niche for now.

**Comment by icefoxen** [comment]
Copied from https://github.com/ggez/ggraphics/#design-thoughts , reposted here for discussion.

----

We should use [wgpu](https://crates.io/crates/wgpu) on the assumption that browsers will implement it
someday, and that will then let us finally Actually Run Stuff In Browser.  Rendy is fine but I'm unconvinced it adds stuff that actually helps us all that much.

Or, you know, if we want to actually run stuff in browser RIGHT NOW, we should use OpenGL... hmmm....

Well, most of this isn't really specific to a particular backend, more thinking about how things
SHOULD be organized.

From ggez's perspective, our options for what we can draw basically are:

 * A single quad with an image
 * A list of quads, each with an image attached and 
 * A list of arbitrary geometry, each with an image attached.

We also have a pile of other state that affects how these are drawn:

 * Drawparam (transform, source UV info, etc.)
 * A canvas (render target).
 * A shader.
 * A bunch of random other state like projection, screen size, transform stack, etc.
 * Glyph-brush image cache

The way ggez does it is super stateful: you set canvas and shader, then you draw a piece of geometry
with an image.  Or many pieces of geometry with the same image.  Either way.

So if we were going to refactor this a little, our types might be

 * Geometry
 * Texture
 * Drawparam
 * Image: geometry+texture
 * Mesh: geometry+texture
 * Spritebatch: geometry+texture+drawparams

So really, our fundamentals are geometry, texture and drawparam.  The differences are mainly in terms
of count and staticness: All Image's have the same geometry, all Mesh's have different geometry, all
members in a Spritebatch have the same geometry and texture, etc.

Most of ggez's geometry is quads.  Is this common enough to be special cased in the actual drawing?
Not sure.

Write usage case first: https://caseymuratori.com/blog_0025 , really ggez's actual drawing API is
quite good for its purpose.  It's basically a list of draw commands.  Or, if shaders or canvases
change, it's a list of `(shader, canvas, draw_commands)`, where each draw command is a list of
`(geometry, texture, drawparam)`.  Soooo, each of those former things is kinda like a Vulkan pipeline.
Ok, not sure where Vulkan render targets happen (I think the relevant type is vkImage though).
However it works, our "pipeline" now looks more or less like this.

```rust
// This is illustrative of how things relate to each other,
// not intended to be how things will actually be implemented.
struct GlobalData {
    geometry: HashMap<VertexIdx, (VertexBuffer, IndexBuffer)>,
    textures: HashMap<TextureIdx, Texture>,
    uniforms: HashMap<UniformIdx, DrawParam>,
}

struct DrawCall {
    geometry: VertexIdx,
    texture: TextureIdx,
    drawparam: UniformIdx,

    // plus...
    sampler: ...,
    shader_instance_parameters: ...,
}

struct Pipeline {
    shaders: Shaders,
    render_target: Canvas,
    commands: Vec<DrawCall>,

    // plus...
    shader_uniform_parameters: ...,
}

struct OtherStuff {
    // plus...
    projection: Matrix4,
    glyph_brush_stuff: ...,
}
```

90% of the time we're only ever using one pipeline.

Some tricky parts: Texture properties (samplers?), shader parameters, operations like texture copies
(used in screenshots, gfx-glyph, etc), not-quite-constrained-to-one-draw-call things like blend
modes, shaders need parameters both per-draw-call and per-pipeline-call (instance and uniform
parameters)...

We also need to make heckin' sure that draw call's and geometry render in the drawn order rather than
overlapping/z-fighting!

Actual features/enhancements we want:

 * Being able to select which adapter to work with
 * Headless mode, for testing
 * Simpler/better handling of the various icky edge cases.
 * Faster (or even automatic) sprite batches.
 * We MIGHT be able to fit the info in DrawCall into a push constant?
 * We want to be able to expose the guts of the underlying graphics system to the user.

Compromises that we make:

 * All textures have the same color format, layout etc.
 * Don't bother with depth buffer, layers, etc
 * We never really have more than one window or Device at once
 * For complicated things, we expose the guts of the underlying graphics system to the user.

Questions to ask:

 * Can we have custom vertex types that get fed into shaders?

**Comment by icefoxen** [comment]
ggez's drawing model might get a bit more declarative in this process.  Right now there's a lot of mutable state which is tucked away in awkward places.

There's a hierarchy of how-variable-stuff-is here as well...  Or rather, which things vary at which stage in the drawing process.

 * Only thing that changes is uniforms.  (drawing spritebatch).
 * Texture and geometry can change.  (drawing Image, Mesh).
 * Texture parameters need to change (modifying sampler)
 * Pipeline needs to change (modifying shader, render target, ??uniforms??)

This currently isn't expressed very well: see #411, #561, #560, etc.  I want to sort it out more so that where you tell things to change matches with where they *actually* change.  This should be good for performance as well.  Whether we make things imperative (user calls `set_pipeline(ctx, pipeline)`) or declarative (user calls `with_pipeline(pipeline, || do_stuff)` or builds a structure of draw calls or something) is really a cosmetic issue, the goal is to cut things along the lines where they divide most nicely.  `set_blend_mode()` and `set_filter()` are great examples of places where properties are kinda located in the wrong places and it makes life weird.

**Comment by icefoxen** [comment]
Okay, here's all the things you can touch:

 * DrawParam -- transform, source rect, color
 * Image -- wrapmode, width/height/color format (for our purposes basically constant), blend mode (through Drawable), 
 * Mesh -- Blend mode (though Drawable), 
 * Shader -- Blend mode, multisampling info, color format (internal), 
 * Canvas -- basically just an Image, size and projection gets a little squirrelly with it though.  That's another rough spot where things aren't being set in the right place and so needs a lot of fix-up.  Multisampling mode, memory binding types, and such are concerns, but purely internal ones.
 * Spritebatch -- texture, blend mode (overriding the blend mode attached to the texture), drawparams.
 * Text -- This needs three things to work: the `GlyphBrush` type which stores its internal cache and whatever else it needs, a texture to actually act as the glyph cache, and a mesh or something (currently a spritebatch) to write glyph geometry into.  Currently these are global in the `GraphicsContext`, but they probably eventually require interacting with `Pipeline`-y settings to work well with other ggez drawing features, such as shaders, blend modes, render targets, etc.  Maybe the glyph cache is its own `Pipeline` that gets given to you when you want to draw text?
 * Globals -- default filter mode *for new images*, projection, text cache data, viewport, blend mode, current canvas, current shader, window stuff.

**Comment by icefoxen** [comment]
What properties SHOULD go where, based on where Vulkan forces you to put them:

 * DrawParam (instance parameters) -- basically stays as it is.  Transform, color, UV source rect.
 * Texture -- `VkImageUsageFlagBits` -- transfer src, dest, etc.  May or may not be the same for all textures but we need to at least worry about it for render targets and screenshots and such.  **Texture arrays may be something we want to use.**  
 * Sampler -- Filter mode, address mode (clamp, tile, etc; `VkSamplerAddressMode`)
 * Shader -- ?????? interpolation modes????
 * Render target -- ?????? just a Texture?
 * Pipeline -- Blend mode

Where does multisampling happen?  In Vulkan, I think it is defined in a render pass; it basically happens between one subpass and the next?  There's a `VkPipelineMultisampleStateCreateInfo` in `VkGraphicsPipelineCreateInfo` though.

**Comment by icefoxen** [comment]
> termhn: you want to separate concept of RenderPass and Pipeline
> RenderPass determines set of possible render targets that all of the contained Pipelines can draw to
and if you need to use the output of a Pipeline in another Pipeline, then they must be in separate RenderPasses
> icefoxen: Tell me more? The connection between the two isn't clear in my mind.
> Aha. So a RenderPass is a set of Pipeline's that do not depend on each other?
> termhn: Yes pretty much
> technically a RenderPass is a aset of Subpasses which each are a set of Pipelines that do not depend on each other
> but you should just only ever use one Subpass for your use case probably
> icefoxen: That's a layer of complexity that I think may not be worth pursuing, but it's worth at least pondering.
> termhn: It's only beneficial in a select few use cases
> mobile deferred rendering being the biggest one
> but that's nota big concern for your case
> So yes, basically RenderPass defines a set of attachments (basically, set of render targets) that its set of contained Pipelines can render into
> in order to sample the output of one of these render targets in a Pipeline, you need to finish the render pass and begin a new one
> RenderPass also controls clearing the render targets
> Pipeline controls blend mode and multisample mode, but the renderpass must agree with pipeline on multisampling

**Comment by icefoxen** [comment]
Ok, this is starting to look like it is going to be *blindingly fast* by default. If you draw a series of things that can be instanced, they will be. Basically everything will be a spritebatch, except without the overhead.

It also maybe offers the option of a more retained-y API as a layer beneath the immediate-y one. Basically just by exposing some of the data structures that are already there and allowing them to be reused from frame to frame. Hmmm. 

Not sure that will actually have significant advantages though. Clearing and re-filling a buffer doesn't seem like it will have much overhead vs. mutating everything in it.

**Comment by icefoxen** [comment]
So we're looking something like this:

```rust
struct InstanceData {
    param: DrawParam
}

struct Batch {
    instances: Vec<InstanceData>,
    geom: Geometry,
    tex: Texture,
    sam: Sampler,
}

struct UniformData {
    camera: Mat4,
}

struct GPipeline {
    shaders: Shader<InstanceData, UniformData>,
    batches: Vec<Batch>,
    uniforms: UniformData,
}
```

Things still to be added to that model: Blend modes, render targets, glyph_brush with all its texture copies (might be its own stage that runs before all the drawing actually happens; run through glyph_brush's stuff to generate its geometry and handle its texture stuff, then create a series of Batch's from that which get drawn at the appropriate time...).

Blending is controlled by `SimpleGraphicsPipelineDesc::colors()`.  I'm not sure exactly where render targets happen yet but it appears to be in the `Graph`, which is several levels above the `Pipeline`; it looks as though it's something like `Graph`'s contain `Pass`'s which contain `SubPass`'s which contain `Pipeline`'s.

**Comment by icefoxen** [comment]
Render targets are indeed controlled by the `Graph`.  So we have something like:

```rust
struct GPass {
    /// run in sequence, more or less
    pipelines: Vec<GPipeline>,
    /// Or something???  I THINK this is right.
    inputs: Vec<Texture>,
    /// Can be a random Texture, or it can be the final render target
    /// which presumably creates a PresentNode
    /// though if the final render target is an image, not sure what to do there.
    output: ImageOrSurface
    clear_color: Color,
}
```

**Comment by termhn** [comment]
@icefoxen you don't need to have input textures for "regular" textures, only ones that you want to be owned by the graph itself and therefore able to be shared (i.e. a render target that you sample in a later pass, what ggez calls a `Canvas`). Otherwise you can just let the `GPipeline` own the texture.

**Comment by icefoxen** [comment]
Yeah, the input textures for `GPass` listed above are intended to be input textures to the pass that gets shared between passes.  Hopefully that makes some sort of sense.

**Comment by omni-viral** [comment]
If by "shared" you mean written by some passes and read by other - then yes

**Comment by icefoxen** [comment]
Okay, it looks like our `GPipeline` corresponds to a rendy `SimpleGraphicsPipeline` more or less, and each `Batch` needs its own descriptor sets.  That might require some thinking about how everything cooperates in terms of buffer data.  Each descriptor set shares the same `Layout` which consists of three bindings, uniform/image/sampler, so that's easy at least, and vertex buffers are kinda a special case.  Each pipeline also has a single set of shaders, and a single `UniformData`, so.

**Comment by omni-viral** [comment]
Note that `SimpleGraphicsPipeline` is called `Simple` because it is simplifiction, good for learning, PoCs and stuff like that.
`RenderGroup` should be used for anything serious in mind.

For instance you would like to create pipelines on the fly which is not feasible with `SimpleGraphicsPipeline` as you'd have rebuild whole graph to insert new one.
Also `RenderGroup` would allow to conveniently share state between pipelines.

**Comment by icefoxen** [comment]
Huzzah, it works!  As of https://github.com/ggez/ggraphics/commit/b49cbb4424ef72deebba22a36f595883690dcffb .  It renders 4 instanced draws of 10k objects at only 15 fps though, on a GTX 1060 on Linux.  I'm probably doing something wrong.

**Comment by icefoxen** [comment]
As termhn suggests, it's probably a matter of overdraw.  Adding a depth buffer makes it work fine, though transparency and draw ordering kinda hecks up because of it, and making the sprites tiny makes it run at 60 fps just fine.

**Comment by icefoxen** [comment]
Draw ordering stuff fixed in https://github.com/ggez/ggraphics/commit/81f2d730a2bed71f5e9af80055909f56a994c31f , and we now have working push constants and stuff.  Feeling pretty okay about my understanding of this, so I'm going to try to rewrite it to use `RenderGroup` as omni-viral suggests.

**Comment by ozkriff** [comment]
How is the development of ggez/ggraphics going, any updates?

**Comment by icefoxen** [comment]
Slow and grumpy. I'm currently waffling between gfx-hal and wgpu. I should probably stop worrying about making everything perfect and just make a Good Enough one.

**Comment by icefoxen** [comment]
Turns out that a Good Enough renderer uses `glow` and WebGL directly. See `ggraphics` branch for example.
