### ISSUE TITLE
Undefined symbol: SDL_GetDisplayDPI while running examples

### ISSUE THREAD

**Issue by Shadlock0133** [ggez/ggez#438]
Tried running examples astroblasto and shader. After running `cargo run --release --example astroblasto` program shows no window and returns with `target/release/examples/astroblasto: symbol lookup error: target/release/examples/astroblasto: undefined symbol: SDL_GetDisplayDPI`

**Comment by icefoxen** [comment]
What version of SDL do you have installed? `SDL_GetDisplayDPI` was added in SDL version 2.0.4.

**Comment by Shadlock0133** [comment]
2.0.8+dfsg1-1ubuntu1.18.04.1

**Comment by icefoxen** [comment]
Bloody GitHub phone version... Sorry for the lack of reply, I've been traveling.

Ok. Now time to get more information. I assume you're using the git master source.  Are there any examples you can run successfully? Can you run `ldd path/to/astroblasto_binary` and post the output?

**Comment by Shadlock0133** [comment]
<pre><font color="#282828"><b>➜  </b></font><font color="#A16946"><b>ggez</b></font> <font color="#B8B8B8"><b>git:(</b></font><font color="#DC9656"><b>master</b></font><font color="#B8B8B8"><b>)</b></font> ldd target/release/examples/astroblasto
	linux-vdso.so.1 (0x00007ffcc2f72000)
	libasound.so.2 =&gt; /usr/lib/x86_64-linux-gnu/libasound.so.2 (0x00007f6fd53b1000)
	libSDL2-2.0.so.0 =&gt; /usr/local/lib/libSDL2-2.0.so.0 (0x00007f6fd5087000)
	libdl.so.2 =&gt; /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f6fd4e83000)
	librt.so.1 =&gt; /lib/x86_64-linux-gnu/librt.so.1 (0x00007f6fd4c7b000)
	libpthread.so.0 =&gt; /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f6fd4a5c000)
	libgcc_s.so.1 =&gt; /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f6fd4844000)
	libc.so.6 =&gt; /lib/x86_64-linux-gnu/libc.so.6 (0x00007f6fd4453000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f6fd5bc4000)
	libm.so.6 =&gt; /lib/x86_64-linux-gnu/libm.so.6 (0x00007f6fd40b5000)
</pre>

I'm can run game-of-life.rs from rust-sdl2 repo. Can't run animation.rs but it's because graphics driver on my laptop only support OpenGL 2.1, I think.

**Comment by icefoxen** [comment]
Awesome, thanks, unfortunately we're not done yet...

`libSDL2-2.0.so.0 => /usr/local/lib/libSDL2-2.0.so.` is the interesting line, it says that it's linking to a copy of SDL that was probably installed from source rather than from the package manager, since it's in `/usr/local`.  However it doesn't list the full SDL version, there's usually symlinks that go from least to most specific version of a library, to let programs (in theory) choose the version they want.

For example, on my machine (Debian):

```
$ ls -l /usr/lib/x86_64-linux-gnu/libSDL2-2.0.so*
lrwxrwxrwx 1 root root   16 Mar  4 06:07 /usr/lib/x86_64-linux-gnu/libSDL2-2.0.so -> libSDL2-2.0.so.0
lrwxrwxrwx 1 root root   20 Mar  4 06:07 /usr/lib/x86_64-linux-gnu/libSDL2-2.0.so.0 -> libSDL2-2.0.so.0.8.0
-rw-r--r-- 1 root root 1.2M Mar  4 06:07 /usr/lib/x86_64-linux-gnu/libSDL2-2.0.so.0.8.0
```

So, I suspect that `ls -l /usr/local/lib/libSDL2-2.0.so*` on your machine will show it eventually goes to a version of `libSDL2.so` < 2.0.4 and that's what you'll have to fix to make it work.  If this isn't the case, we will see what we can do to keep troubleshooting.

**Comment by Shadlock0133** [comment]
Thank you very much for help.

If anyone looks for exact solution, you need to either uninstall (and use distribution provided package) or update your SDL installed from source.
1. Download and unpack SDL source code.
2. `./configure`
3. Either `sudo make uninstall` or `make && sudo make install`
