### ISSUE TITLE
[bug] offset + custom screen coordinates

### ISSUE THREAD

**Issue by ozkriff** [ggez/ggez#439]
Offset moves image to a strange position when used with custom [-1..+1] coordinate system

Demo repository with two binaries: https://github.com/ozkriff/ggez_scale_offest_bug_demo

![](https://raw.githubusercontent.com/ozkriff/ggez_scale_offest_bug_demo/master/demo.png)

^ These test apps are supposed to give similar results, but in `absolute_coords` image's offset moves it to a strange position - towards the edge of the screen.

(maybe this issue is related to #435)

-------

UPD: Results in _this_ for Zemeroth:

![image](https://user-images.githubusercontent.com/662976/43050071-b2f119d2-8e0b-11e8-8075-821cde3cc049.png)

**Comment by icefoxen** [comment]
Is this on the master branch or devel?

**Comment by ozkriff** [comment]
0.4.3

**Comment by icefoxen** [comment]
Well, crap.

**Comment by robojumper** [comment]
How is `offset` supposed to work? Both examples produce results that are inconsistent with the documentation, which states:

```
    /// specifies an offset from the center for transform operations like scale/rotation,
    /// with `0,0` meaning the origin and `1,1` meaning the opposite corner from the origin.
    /// By default these operations are done from the top-left corner, so to rotate something
    /// from the center specify `Point2::new(0.5, 0.5)` here.
```
yet window_coords shows that this affects the translation too.

Code for reference: https://github.com/ggez/ggez/blob/98c37ba539a015eb881072529e60b3772ede299c/src/graphics/drawparam.rs#L78

Making both examples produce the same result is a simple as removing the `* offset` multiplication from this, while making both examples consistent with the documentation (also producing the same result) is a matter of changing

https://github.com/ggez/ggez/blob/98c37ba539a015eb881072529e60b3772ede299c/src/graphics/drawparam.rs#L54

to 

    let offset = Matrix4::new_translation(&Vec3::new(self.offset.x * self.scale.x, self.offset.y * self.scale.y, 0.0));

because in the formula, `offset_inverse` is affected by `scale`, while `offset` is not.

**Comment by ozkriff** [comment]
The bug is still there in `0.5.0-rc.0`, though I confirm that the fix from @robojumper _seems_ to work.

**Comment by PSteinhaus** [comment]
> `translate * offset * rotation * shear * scale * offset_inverse`

This was the source of this problem, indeed. Multiplying `offset` into this matrix just didn't make any sense, so we removed it in #880. I'm pretty sure this fixed the problem, therefore I'm closing this now.
