### ISSUE TITLE
Add docs/explanation for Drawable::draw() src and dst parameters.

### ISSUE THREAD

**Issue by onelson** [ggez/ggez#44]
Coming from other frameworks, the methods for drawing stuff to the window might accept a graphic, position (x, y), and potentially some extended transform data (rotation, scale).

This time we have `src`, and `dst` (a pair of `Option<Rect>`) and it's not immediately obvious to me what the intent is. Fumbling around, I managed to get a graphic in the center of the window by supplying `None` as the `src` and `dst` by creating a `Rect` with the appropriate x/y and width/height to match the image, effectively setting the bounding box for where the image should be drawn.

Really not sure how `src` would be used, or if I'm even doing what would be expected for this simple case.

**Comment by icefoxen** [comment]
Unfortuantely it's very directly determined by SDL2.  Which has a pretty lousy API for it.  If `src` is `None`, it takes the whole image as the source, which is usually what you want.  If `dest` is `None`, it takes the whole destination image as the destination, which is usually not what you want.  If either is `Some(Rect)`, the rect is the bounding box for the source or destination.

`src` is intended to be used to implement something like a sprite sheet, where you have one image and draw many sub-sections of it, which is generally a little easier than the graphics hardware than drawing many different images.

It's all generally pretty inconvenient and I'm looking forward to replacing it.  Especially since SDL gives you no real control over how it does scaling or such.  Love2D's API is rather nicer.

**Comment by onelson** [comment]
OK, that's a great summary, but if it takes a couple paragraphs to express, it's probably not where we want to be ;)

SDL is not doing any favors here in terms of simplicity, but we should be able to provide a Love-like abstraction over this. Cool.

With `src` as a view into the image data, and `dst` having a size and position, that should give us translation, rotation (at least in `Drawable::draw_ex()`), and scale (relative size from `src` -> `dst`).

**Comment by icefoxen** [comment]
I'm working on drawing with gfx-rs right now and it looks like it's going to be a bit of work but much simpler and more powerful in the end.  My plan is basically to replicate SDL's drawing API with gfx and make that version 0.3, which we can release without *totally* changing the API and work the kinks out, then version 0.4 will revamp the graphics API.

Check out the `gfx` branch in this repository, though the only thing that works is the `triangle` example.  :-)

**Comment by icefoxen** [comment]
Now that I've talked about that plan I actually did something completely different in https://github.com/ggez/ggez/commit/644ae28a964d78c5d7cc73f04dcfee1e4fed8361 .  Love2D's drawing API is saner and simpler to implement so we're just going to use that.

What we DO still need is documentation for all that though!

**Comment by onelson** [comment]
Ha! I'll work up the docs based on your explanation (for the master branch). The `src`/`dst` API actually makes a lot of sense for sprite sheets - I wonder if we could have both, but promote the love-style for general use (since it is a lot more obvious to reason about).

**Comment by icefoxen** [comment]
love has the same option, it's just saner by default.

**Comment by icefoxen** [comment]
Also I'm not sure it's worth documenting the master branch right now since it's going to get replaced with the gfx branch in the next release, even if it drives me insane.

**Comment by icefoxen** [comment]
Done!
