### ISSUE TITLE
Add ability to integrate a .zip file into a binary

### ISSUE THREAD

**Issue by icefoxen** [ggez/ggez#469]
@svenstaro mentioned this and it was a cool idea, being able to make a build.rs that zips up your resources directory and then include it into your .exe with `include_bytes!`.  It should take a quite minor extension to the `vfs` module to do, and it would be cool and useful (if not always the most efficient) to be able to bundle all your assets into a single .exe.

We've pondered things like this before but the idea of just using a zip file or similar archive instead of having to write one's own in-memory vfs is new.

**Comment by andreivasiliu** [comment]
Trying to get my thoughts together here, ignore me (PR later).

`ZipFS::new()` only takes a filename, I'll likely refactor it to use a `ZipFS::from_file<F: Stuff>(file: F)`, and also add a `ZipFS::from_bytes()` that gives `from_file(std::io::Cursor::new(bytes))`. Maybe I should rename `::new()` to `::from_path()` but I don't know what that would break.

How does a user pass the bytes to ggez? I'm thinking:
```
ContextBuilder::add_zipfile_bytes(self, Vec<u8>) -> Self
ContextBuilder::add_file_bytes(self, contents: Vec<u8>, mount_path: P) -> Self  # won't implement here

ctx_builder
    .add_zipfile_bytes(include_bytes!("resources.zip"))
```

The new resource loading order will be:
* The resources/ subdirectory
* The resources.zip file
* The root folder of the game's "save" directory
* Paths from `.add_resource_path()`
* Zipfiles from `add_zipfile_bytes()` ***New!***

**Comment by andreivasiliu** [comment]
Actually, now that I look at it, it's kinda silly to force the user into giving bytes, when a `Read+Seek` is a universal interface that could be used for all sorts of fun stuff.

Hey @icefoxen - rather than bytes, would you be okay with allowing users to give any file instead? The user code would look like this:
```
ContextBuilder::add_zip_file<R: Read+Seek>(self, reader: R) -> Self

ctx_builder
    .add_zip_file(std::io::Cursor::new(include_bytes!("resources.zip")))
```
Which is, yeah, a lot longer, but a lot more powerful.

**Comment by icefoxen** [comment]
That looks reasonable to me.  Bytes and read+seek are good at different things, but for this case I think read+seek would be a fine choice.

In terms of naming, the ggez convention is that when creating a resource such as image or file, `Foo::new()` takes a path and there's also `Foo::from_bytes()` or `Foo::from_read()` or whatever that takes something lower-level.

Not sure about the resource load order, but your proposal seems reasonable and it's easy to change later, so let's go with that.

**Comment by andreivasiliu** [comment]
Alrighty then. I'll try getting a PR ready next weekend.

**Comment by andreivasiliu** [comment]
Stumbled upon a blocker: ContextBuilder has to be Clone. This means boxing the user-provided Seek+Read object for later, and somehow making it cloneable. Asking the user to provide a Clone implementation is impossible, because Box<dyn T> (or rather dyn T itself) does not support things that have Clone.

Alternatives:
* I could just skip the context builder and add a method directly to the Filesystem; however, the filesystem currently has no public methods (not sure why?), and I'd be adding the first one.
* I can ask the user to give a boxable function that generates a reader instead, but it makes the user code look weird: `ctx.add_zip_file(|| std::io::Cursor::new(include_bytes!("stuff.zip"))`
* Allow it, but panic if the user tries to clone a contextbuilder with any trait objects inside it
* I can lose the whole Read+Seek idea and only implement .from_bytes for now, which ContextBuilder clones and wraps in a Rc<Vec<u8>> or something.

**Comment by icefoxen** [comment]
I'm not entirely sure where the problem is just from that description; do you have some sort of code example somewhere?  I'm a bit slow this weekend it seems.

The `Filesystem` having no public methods is intentional, basically there was a divide between "make everything methods on an object" and "make everything functions in a module that takes a `Context`" and the latter seemed more reasonable.  The only reason the `Filesystem` object is public is basically for occasional debugging.

Dumb answer: Can you just define the trait object to be `Read+Seek+Clone`?  It looks like `io::Cursor<T>` is `Clone` as long as `T` is.

**Comment by andreivasiliu** [comment]
I went with supporting just from_bytes for now. And no, a trait object cannot be Clone, ever, which is something I learned today. :(
https://www.reddit.com/r/rust/comments/7q3bz8/trait_object_with_clone/dsm8pdf/

**Comment by andreivasiliu** [comment]
Here's a small example to showcase the Clone error:
https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=d6d913ea5baea84bfa46f79c2108bede

**Comment by icefoxen** [comment]
Done in #622
