### ISSUE TITLE
Get pre-named color definitions.

### ISSUE THREAD

**Issue by icefoxen** [ggez/ggez#54]
Incorporate the `palette` crate?

Or at least make an easy way to use it.  It's pretty awesome.

**Comment by icefoxen** [comment]
So far not having an external color library has not hurt us at all, though it still *would* be nice to have a big ol' list of pre-defined colors somewhere, built and maintained by someone not me.  :D

**Comment by itmuckel** [comment]
I use the palette library in the game I'm making. But at least some basic colors would be nice to have.

**Comment by Eayu** [comment]
I think it would make sense to have the colors as associated constants for Color - this way the colors can be accessed like `Color::WHITE` rather than `graphics::WHITE`, which seems more idiomatic. Obviously the disadvantage of doing this is that it would require current uses of the BLACK and WHITE constants to be changed in users' codebases.

How many colors do you have in mind? This list seems quite good: https://sashat.me/2017/01/11/list-of-20-simple-distinct-colors/

**Comment by icefoxen** [comment]
> How many colors do you have in mind?

That's a good question!  My instinct says "All of them", but I certainly don't want to write them, hence the desire to outsource the problem to another crate.  :-P

It probably wouldn't be hard to add a feature flag to import the `palette` crate and implement `From` conversions to and from its types (handling sRGB correctly).  That might be the best way to go.

**Comment by Eayu** [comment]
To be honest I think importing the palette crate might be overkill, even behind a feature flag, when all we really want is some predefined colors. It seems a bit messy having ggez's own `Color` struct, along with all of palette's structs as well - I think if we deem palette's functionality that important, it would be better just to add it as a full dependency and use their color structs instead of ggez's own.

I would be happy to write some predefined colors constants, and more can be added in the future if we feel we are missing some.

**Comment by icefoxen** [comment]
In that case, sure, go for it; the list of 20 you posted seems pretty reasonable.  I'd just make them top-level consts in a new module `graphics/colors.rs`, though making them associated consts on `Color` would also work.  Up to you.

If you do this, leave the existing `WHITE` and `BLACK` color consts in place, mark them depreciated, and we can put this change in the next point release.

**Comment by Eayu** [comment]
If a lot of people are using `palette` with `ggez` anyway then I guess it makes sense to integrate it. I'm not sure what's the right call here, so I'll leave it up to you. Either way I'm happy to help implement it.

**Comment by icefoxen** [comment]
Just occured to me, another option is to just add a feature dependency on `palette` and a module re-exporting `palette::named` when that feature is enabled.  Those are all defined as `(u8, u8, u8)` , and `ggez::graphics::Color` already implements `From<(u8, u8, u8)>`.

**Comment by icefoxen** [comment]
Honestly, nobody has really asked for this, and it's easy enough to incorporate the `palette` crate if you want to.  So, meh.

**Comment by icefoxen** [comment]
I've gotten sick of `palette` and related crates having far too much STUFF in them, and so have created the [`chromatic`](https://github.com/icefoxen/chromatic/) crate to provide JUST simple color definitions.

**Comment by icefoxen** [comment]
`chromatic` is now published on crates.io as the name `chromatica`, 'cause `chromatic` was already taken.
