### ISSUE TITLE
Framerate seems uncapped, CPU usage very high, jitter, seems unrelated to screen refresh (macOS Mojave)

### ISSUE THREAD

**Issue by chrishulbert** [ggez/ggez#541]
Thanks for ggez, it looks great so far.
I've run through a bunch of the examples and they all seem to have the same symptoms: 

* Extremely high CPU usage for such simple examples, which makes developing on a laptop very difficult as it gets hot and drains the battery. I'm running in release mode.
* Even when WindowSetup.vsync = true as per default, it generates much much more than 60fps. I expected this to cap the framerate/cpu usage, am i misunderstanding this somehow?
* When running extremely simple demos of things moving across the screen, it's clear to the naked eye that frames are being dropped and the movement isn't smooth, and isn't correctly synced to the natural screen framerate - it looks jarring.

It seems to me that the common thread among these issues is syncing with the screen's refresh rate, am i doing something wrong here?
Thanks

**Comment by icefoxen** [comment]
That is very very weird. I don't have a Mac so can't reproduce myself, but I'll get other people to tap in if possible. If you have any experience with profiling tools, a profile of some kind taken for one of the examples would be very useful.

In the mean time, do you have the same problem when running the `gfx-rs` examples, for the 0.17 branch?

**Comment by chrishulbert** [comment]
Thanks for the response :)
I got gfx-rs 0.17 running, and most of the examples fail to build on macOS. The 'shadow' example works however, and seems nontrivial thus a reasonable example. I added a framecounter like so to the end of the render method:
`        self.frame_counter += 1;
        if self.frame_counter > 1000 {
            let elapsed = self.instant.elapsed();
            println!("{} frames, {:?}", self.frame_counter, elapsed);

            self.frame_counter = 0;
            self.instant = Instant::now();
        }`
And i can figure that it's running at roughly 500FPS. So it's clearly not capping to the vsync :) I can't see how to enable vsync with gfx, i'm not sure of the way forwards here.

**Comment by armyofevilrobots** [comment]
I am seeing the exact same thing here. Additionally, when I try and limit the frame right with this code (which gets called every update or draw, either makes no diffrence), it runs about 1.5x as fast as I would expect. It's possible (likely even) that I am making some silly mistake because I am a n00b, but 🤷‍♂️ 

Also, I do see some loops where the reported duration of a frame is longer than desired FPS would imply, but I would expect this if something preempts the game loop...

`
pub fn sleep_until_next_frame(ctx: &Context, desired_fps: u32) {
    dbg!(timer::delta(ctx));
    let target_dt: f64 = 1.0 / f64::from(desired_fps);
    let dt = timer::duration_to_f64(timer::delta(ctx));
    if target_dt - dt > 0.0 {
        let sleep_duration = timer::f64_to_duration(target_dt - dt);
        println!("Sleep duration is {:?}", sleep_duration);
        thread::sleep(sleep_duration);
    }
}
`

**Comment by icefoxen** [comment]
@armyofevilrobots Thank you, is this also on Mojave?

Do the examples and such run faster than you expect as well?  That's an easy way to check whether the problem is in your timing code or in ggez's timing functions.  One possible edge case is that `thread::sleep()` is not necessarily 100% precise; if you ask to sleep for 16 ms it may sleep for 16 ms or 19 ms or whatever the OS decides it can give you.  For details on the best way to do timing for games, this article is the best I've ever seen: http://gafferongames.com/game-physics/fix-your-timestep/

**Comment by icefoxen** [comment]
I'm dropping support for Mac, so. cry See #587 for basically the reason why.

**Comment by chrishulbert** [comment]
I think you made a wise choice :) Thanks for all your hard work on this framework!
