### ISSUE TITLE
`SpriteBatch` is slow as heck in debug mode

### ISSUE THREAD

**Issue by icefoxen** [ggez/ggez#548]
This has been true forever, but since it is now used to draw text glyphs it is a little more painful.  I did some profiling and it looks like most of the overhead is in the math to turn `DrawParam` into matrices and related transformations; see if it's possible to optimize it more just by doing the matrix stuff a bit more cleverly.  It's currently rather brute-force.

**Comment by okunnig** [comment]
Any specific idea on how to progress with this? Any rough idea on how much performance there is to gain?

I suppose you can push parts of DrawParam to the GPU and do the transformations in the vertexshader but I'm not sure if it's a good idea.

**Comment by icefoxen** [comment]
Theoretically, "how much performance there is to gain" is the performance gain in spritebatch in debug vs. release mode.  Which is at least 100x.

First step would be to profile it (the `spritebatch` example is a good test case) and double-check my conclusions.  If correct, I'd take a look at https://github.com/ggez/ggez/blob/master/src/graphics/drawparam.rs#L110-L119 and see if it can be made... well, less clean and clear.  It constructs a lot of matrices through function calls, then multiplies them all together, which does a lot of redundant math to redundant objects.  You can probably get at least a bit of milage out of just replacing two `Matrix4::new_whatever` calls with constructing a matrix that combines several transformations at once.

Lemme know if you need more of an introduction than that.

**Comment by okunnig** [comment]
Thanks for the guidance! I'm still new to ggez.

So I've looked a bit at this. I used perf on linux and rust 1.32 to profile the spritebatch example. It indeed seems that `to_matrix` is rather slow in debug mode. Reimplemented the transformation matrices in `to_matrix` by hand which bumped the delta frame time from ~2.4s to ~240ms. You can see the test implementation at https://github.com/okunnig/ggez/blob/opt/drawparam/src/graphics/drawparam.rs#L144-L171.

Profiling again with the above fix in place shows that `ggez::graphics::present` might be the next slow call (the cost lies deep in gfx). Rust is generally slow for non optimized builds. I'm not sure where to continue from here regarding debug build performance.

However, I also profiled the spritebatch example for a release build and we can gain a bit of performance there by tweaking the `to_matrix` function. The implementation at https://github.com/okunnig/ggez/blob/d44b20f3f301341064523af470e2630f317ba4cd/src/graphics/drawparam.rs#L111-L133 performs the transformations with 3x3 matrices and seems to give better performance (while being somewhat maintainable) although it doesn't seem quite as fast as the handmade version.

Oh, and finally, the color conversions also showed up when profiling the release build. This might not be the issue for that but would it be a good idea to skip conversions for color components which are close to 0.0 and 1.0 in order to gain some performance when not blending much? The point would be to catch white or black colors.

**Comment by icefoxen** [comment]
Very, very nice work. I'll double-check it and pull in the changes you reference when I get the chance. The main worry is that, as you can see by various other recent issues, transform math is kinda touchy and I'm not very good at it, so any change to it I make with some hesitation. :-p

`ggez::graphics::present` being the bottleneck in debug mode is more ok. The gfx-rs OpenGL backend builds a literal Vec of graphics commands and then iterates over them to execute each in turn, which involves lots of bounds checks and such in debug mode that all vanish in release. I did some work back in the Dark Ages of 2016 or something to improve it, and there's still some fairly low-hanging fruit to be plucked there if you want to dig into gfx-rs 0.17, but that's something I'm a lot less worried about.

**Comment by icefoxen** [comment]
Oh, I seeeeeeeee.  Perhaps the best way actually would be to do the sRGB math on the GPU.  Or just try to micro-optimize that function some.  That's definitely worth thinking about.

**Comment by icefoxen** [comment]
Resolved by #716 .  Huzzah!
