### ISSUE TITLE
Move blend mode from Drawable to DrawParams

### ISSUE THREAD

**Issue by ozkriff** [ggez/ggez#560]
Why is (`set_`)`blend_mode` a part of the `Drawable` trait and not just a field of `DrawParams`? I can't see any complex logic in any `Drawable::set_blend_mode` implementation.

**Comment by icefoxen** [comment]
Check out where the `blend_mode` is used now that I think of it.  I vaguely recall gfx-rs wanting it that way.

If we can put it in `DrawParams`, it might be nice.  Though I wonder if it would work in `SpriteBatch` in that case, since idk if you can have instanced drawing with different blend modes per instance.

**Comment by PSteinhaus** [comment]
Blend modes are now no longer set per `Drawable`. Now, with the wgpu-PR merged, they're part of `Canvas`' state.
We could have also moved them to `DrawParam`, leading to them being included in the queue maintained inside of `Canvas`, but for now I think having blend mode be one of the two values in the internal-state-queue of `Canvas` (together with the shader used by it) makes sense.
