### ISSUE TITLE
FilterMode::Nearest on Text in 0.5

### ISSUE THREAD

**Issue by eqv** [ggez/ggez#561]
It seems that there is no way of specifying the filtermode for fonts in 0.5.

If you still want to have crisp looking fonts you can use the following workaround:

```rust
            desc.set_font(*font, Scale::uniform(128.0)); //pick a large resolution for the font
            //desc.set_filter(graphics::FilterMode::Nearest); //doesnt work anymore
            graphics::draw(
                ctx,
                &desc,
                graphics::DrawParam::default()
                    .dest(Point::new(x,y))
                    .scale(Vector::new(0.2, 0.2)) //and scale it down for displaying
            )?;
```

**Comment by icefoxen** [comment]
Hmmm, yeah that's marked as WIP in the source.  I guess we need to progress it.  Thank you!

**Comment by tverghis** [comment]
I did a bit of digging around for this issue, but noticed that [`ggez::graphics::Text`](https://docs.rs/ggez/0.5.0-rc.1/ggez/graphics/struct.Text.html`) doesn't have a `set_filter` method (it only exists on the `Image` struct). There is, however, a `blend_mode` property on `Text` that doesn't do anything currently. Is that what this issue should be addressing?

**Comment by icefoxen** [comment]
@tverghis Nah, we need to add a `set_filter()` method on `Text`.  ALONG with making `blend_mode()` do something.

This is actually kinda non-trivial since text all gets shoved into a *global* spritebatch upon being queued, so if two `Text`'s have different `FilterMode`'s it just won't work.  We can't have a spritebatch that draws a bunch of stuff with one filter mode, switches, then draws other stuff.  Blending is a similar problem.  `glyph-brush` doesn't directly allow you to manipulate these either, really; they're properties of the texture you're giving it to use as a cache.

We probably need *global* `set_text_filter()` and `set_text_blend()` functions or something.  This is rather awful but I don't see a better way around it.  :-/

**Comment by icefoxen** [comment]
Well, it's implemented, though it's not a solution that is without new problems of its own.  (And it needs testing.)

Basically, both `BlendMode` and `FilterMode` both need to be provided to `draw_queued_text()`, and will apply to ALL text in the queue.  This is for fairly fundamental reasons about how the GPU shares data between the things it draws.  `Drawable` is really kind of the wrong abstraction for that, because it connects things that don't need to be connected, and makes things unconnected that should be.

https://github.com/ggez/ggez/issues/418#issuecomment-486747786 and a lot of my related ramblings in https://github.com/ggez/ggraphics are basically me trying to explore this very problem: what are all the options for drawing stuff, and at what level are they specified?  Most fundamental are vertex inputs, which is what `SpriteBatch` and `glyph_brush` deals with: drawing vertices as fast as possible by drawing as many vertices as possible without needing to change anything else.  Vertex and instance data are the only things that change.  The level above that is a draw call, where you specify your texture, sampler (texture properties such as filter mode), and mesh/instance buffers.  Those are all inputs to a single draw call.  Then above that you have a pipeline, which specifies shader programs, uniforms and other properties about how to combine multiple draw calls -- such as blend mode.  Switching pipelines is expensive so you want to do it as seldom as possible.  But ggez's `Drawable` lets you pretend switching a blend mode happens at the same time you switch a texture or mesh!

So ggez's current drawing model is flawed, and I'm not going to try to hack around it more than I already have.  I hope to fix it in a future version of ggez, but I don't even know what it's going to look like yet -- a lot of the work on `ggraphics` so far is me trying to figure it out.

**Comment by icefoxen** [comment]
Well, tested and they work, at least.  Closing, but feel free to re-open for discussion.
