### ISSUE TITLE
Document the idiomatic way of error handling

### ISSUE THREAD

**Issue by ozkriff** [ggez/ggez#590]
A game's code is supposed to have its own error type (that can wrap over `ggez::GameError`) but you are forced to `unwrap`/`expect` all your errors in `EventHandler`'s `draw` and `update` methods (because you can't turn them into `GameError`), right? Is this documented somewhere?

Related to https://github.com/ggez/ggez/issues/421

**Comment by icefoxen** [comment]
Not documented anywhere 'cause I haven't really thought about it, 'cause I haven't yet made a large enough game with ggez to encounter problem.  If I wanted to handle errors without panicking I guess I'd like, have an error log in your main state or something and if `draw()` or `update()` gets an error they'd save it to that and print it somewhere?  Or something.  Do you have any good ideas?

**Comment by ozkriff** [comment]
If an application's author knows that some errors are not critical - then yeah, logging and dropping them is fine. If we're not sure of how critical the error is, then panicking seems to be the only safe choice.

**Comment by ozkriff** [comment]
Another question, that went through my mind while I was implementing https://github.com/ozkriff/zemeroth/pull/433, is why `draw`/`update` return `GameResult` at all? Like, the only thing that can be done with errors (both GGEZ's and game's specific) at this step is panicking anyway (and that's what `event::run` does).

**Comment by icefoxen** [comment]
Mostly so that I can use `?` instead of `unwrap()` inside them so it's quicker to type.

**Comment by icefoxen** [comment]
Ozkriff, a better response to your second question: https://github.com/ggez/ggez/issues/512

**Comment by JeanMertz** [comment]
I came here looking for an answer to this question as well.

I want to be able to test different components of my (experimental, for fun) game in isolation, which also means I'd like them to return "my" error type instead of ggez's.

I'm using [`thiserror`](https://docs.rs/thiserror) and basically do something like this in my isoldated `update` logic:

```rust
/// Game update related error
#[derive(Debug, Display, Error)]
pub enum Updater {
    /// plugin runtime error
    PluginRuntime(#[from] Runtime),

    /// game engine error
    GameEngine(#[from] ggez::GameError),
}
```

This basically allows me to capture my own errors in a structured manner, and have all ggez-related errors be captured by the `GameEngine` variant.

The problem of course is once this error propagates to `EventHandler::update`, I now have to shoe-horn all my non `GameEngine` errors either into one of the existing `ggez::GameError` variants, drop all non-ggez errors, or panic.

Ideally all the errors could propagate up through `event::run` so that I can then decide what I want to do, but I realize that's probably difficult to achieve (given that the window would already be closed at this point, so there's no way to show errors through the UI, the only alternative being, logging the error).

I don't really have a solution to present, but I thought another "use-case" of wanting to use my own error types but not really knowing what to do once I reach the update/render boundary.

What I'll probably end up doing is: wrap my updater to log any errors it receives, and then in `EventHandler::update` either return the `GameEngine` error variant if applicable, or move any other error into `GameError::RenderError(err.to_string())`.

I guess it would be nice if there was a `UpdaterError` variant, as that would fit better as an "any non-ggez error" variant in `EventHandler::update`

**Comment by icefoxen** [comment]
Out of curiousity, what do you intend to actually do with your errors after they pass out of the `event::run()` boundary?  One of the main reasons I have for not doing anything special for this workflow is that generally all I'd want to do with the errors anyway is a) log them and keep going, or b) panic and stop.  And both of those are handled just fine inside the `EventHandler`.

**Comment by Grinshpon** [comment]
I'm not sure if this is the right thread, but I think `GameError` should have a variant for custom errors

**Comment by PSteinhaus** [comment]
> I'm not sure if this is the right thread, but I think GameError should have a variant for custom errors so that there's no need to create a wrapper around it or GameResult

This has now been implemented. Also, one is now free to return any given kind of Error in EventHandler.

So what appears to have been the main problem here is now no longer a problem. The last remaining thing is probably that we might want to add an example showcasing error handling?
