### ISSUE TITLE
unable to create window WindowCreationError

### ISSUE THREAD

**Issue by MikeeyBikeey** [ggez/ggez#597]
When I run any of the examples it panics:
```
cargo run --example 01_super_simple
    Finished dev [unoptimized + debuginfo] target(s) in 0.94s
     Running `target\debug\examples\01_super_simple.exe`
Error: WindowCreationError(NotSupported("required extension \"WGL_ARB_create_context_profile\" not found"))
error: process didn't exit successfully: `target\debug\examples\01_super_simple.exe` (exit code: 1)
```
I'm on windows 10

(Graphics and rust are still new to me, so I might not know some terminology)

**Comment by icefoxen** [comment]
That's a new one, thank you! What GPU do you hav

**Comment by MikeeyBikeey** [comment]
Is this what you mean:
Card name: Intel(R) HD Graphics

Sorry this is my first time checking my GPU, please let me know if you more information

**Comment by Hero9909** [comment]
can you post your opengl version and an detailed name of your cpu?
this might happen if your gpu ( here the intel chipset ) is missing support for an extension. 

if you dont know or unshure , here is an link to some cpu versions (62) maybe you can find your opengl version there. There is althought an video how to get some informations if you have "Intel control panel" installed
[Link to intel Driver and version page](https://www.intel.de/content/www/de/de/support/articles/000005524/graphics-drivers.html)

**Comment by MikeeyBikeey** [comment]
I followed the video ["Link to intel Driver and version page"](https://www.intel.com/content/www/us/en/support/articles/000005524/graphics-drivers.html), here's what I got:

```
Intel(R) HD Graphics

Report Date:			3/4/2019
Report Time[hh:mm:ss]:		13:58:27
Driver Version:			9.17.10.4459
Operating System:		Microsoft Windows 10 Home(10.0.17763)
Default Language:		English (United States)
DirectX* Version:		11.0
Physical Memory:		3909 MB
Processor:			Intel(R) Pentium(R) CPU B960 @ 2.20GHz
Processor Speed:		2195 MHz

... (It shows more information)
```
This is where the video led me [Intel® Pentium® Processor B960](https://ark.intel.com/content/www/us/en/ark/products/59836/intel-pentium-processor-b960-2m-cache-2-20-ghz.html)

I couldn't find anything about my opengl version.
Please let me know if you need more information.

**Comment by Hero9909** [comment]
[Link to Open GL Extension Viewer](http://realtech-vr.com/admin/glview) 
This application lists the available extensions supported by your proccessor and driver. as of OpenGL 3.0 (some opengl 2 implementations althought) allowing an easy listening of your availabe extensions .

Ive searched for an decent driver thats supporting the **W**indows Open**gl** extension, but sadly there is no result i can present you. 

So all together, this means if your proccessor isnt listening with the application the extensions your error is complaining about. it´ll likely that you wont find a driver that supports this extension, and therefore you wont be abled to run this example. IF the extensions is listed, i would take this as an bug or an misconfiguration in your os. in this case it would be usefull to post an run with the verbose flag.

im hope this clarifies this error for you.

**Comment by icefoxen** [comment]
Thank you for the info, and thanks for picking up some of the slack on troubleshooting, @Hero9909 .  Been a busy week.  :-)  

Intel CPU's all have embedded GPU since like 2008, so looking up [the specs](https://ark.intel.com/content/www/us/en/ark/products/59836/intel-pentium-processor-b960-2m-cache-2-20-ghz.html) we see the graphics chip described as "Intel® HD Graphics for 2nd Generation Intel® Processors".  Finding [this](https://software.intel.com/en-us/articles/quick-reference-guide-to-2nd-generation-intel-core-processor-graphics-hd-graphics) and digging through it, this equates to Intel HD 2000/3000 GPU's, which... are, unfortunately, the very tail end of the era in which Intel GPU's were utter shit.  Max OpenGL support 3.1, not great support for a lot of features.  It's just *old*, and supporting old hardware is a lot of work. so unfortunately you may be out of luck. :cry: 

(Note to self: a better compatibility matrix is [here](https://www.intel.com/content/www/us/en/support/articles/000005524/graphics-drivers.html) .)

Let's see if we can work around it though.  Entertainingly, `WGL_ARB_create_context_profile` is the extension that lets you do better version checking to see what features the driver supports... and your driver doesn't support it.  Asking for OpenGL 3.1 when [building your context](https://docs.rs/ggez/0.5.0-rc.1/ggez/struct.ContextBuilder.html#method.backend) may help, or at least can't hurt.  Digging into `glutin`, it looks like the call to create the OpenGL context with `wglCreateContextAttribsARB()` is [here](https://github.com/tomaka/glutin/blob/c0b36056bdacdcef989f518d6d17307ac85f0da2/src/api/wgl/mod.rs#L417), but if you don't pass any options to it, it will [use the more old-fashioned function to create it here](https://github.com/tomaka/glutin/blob/c0b36056bdacdcef989f518d6d17307ac85f0da2/src/api/wgl/mod.rs#L436).  But [gfx_window_glutin](https://github.com/gfx-rs/gfx/blob/v0.18/src/window/glutin/src/lib.rs#L140) passes a pile of options to it no matter what you do.

So... yeah, it's fixable, if we go into `gfx_window_glutin` and make an option for it to attempt to create a window with no options, and adapt ggez to use it, and `glutin`'s sooooorta-documented behavior of how this gets used doesn't change (which it probably won't, but still).  This is why supporting old hardware is a lot of work.  :-(

**Comment by MikeeyBikeey** [comment]
I changed the opengl version to 3.1, but I got the same error.

I was going to modify gfx_window_glutin and stuff, but luckily, my other computers can use ggez! And thanks to your information I was able to get a different graphics crate to work.

So, I'll use both ggez and  the other graphics crate.

Thanks for your awesome help and support.
