### ISSUE TITLE
Decide whether it's called a `Gamepad` or a `Controller` :-|

### ISSUE THREAD

**Issue by icefoxen** [ggez/ggez#614]
We use both in different places, it seems.  "Controller" is more generic but `gilrs` uses "Gamepad".

**Comment by kampffrosch94** [comment]
According to wikipedia https://en.wikipedia.org/wiki/Game_controller a controller can mean things other than game pads, a steering wheel for instance. Because ggez only handles Gamepads atm I think Gamepad is the better name.
It can still be renamed later, if support for other kinds of controllers are added.

**Comment by icefoxen** [comment]
Settled on "gamepad" in commit 8151006.  We were mostly there anyway, and "Controller" can be used for awfully vague programmer-y terms, so let's be unambiguous.
