### ISSUE TITLE
Degenerate cases of meshes cause runtime failures

### ISSUE THREAD

**Issue by Voker57** [ggez/ggez#671]
**Describe the bug**
For example, lines and circles that are a effectively single point produce cryptic errors:
```
Error: LyonError("Trying to build mesh with < 3 vertices, this is usually due to invalid input to a `Mesh` or MeshBuilder`.")
```

**To Reproduce**
```
graphics::Mesh::new_circle(
            ctx,
            graphics::DrawMode::fill(),
            na::Point2::new(0.0, 0.0),
            0.0,
            1.0,
            graphics::WHITE,
        )?;
```
**Expected behavior**
Draw a point.

**Screenshots or pasted code**

**Hardware and Software:**
 - ggez version: current git master

**Comment by icefoxen** [comment]
I would rather think that asking for geometry with a size of 0 would come under the heading of "invalid input".  Is that more or less confusing than not drawing anything at all?  :man_shrugging: 

See https://mattdesl.svbtle.com/drawing-lines-is-hard for some of the issues involved.  If you want to be able to make a point that is a single pixel, I recommend using an `Image` instead, or make your geometry be actually a single pixel across instead of no pixels across.

**Comment by Voker57** [comment]
I see the problem.

Maybe, a high-level API that knows how to handle such cases is in order? I'm drawing a circle of radius based on zoom level and it's not nice that at certain size it just breaks.

At very least, the issue should be mentioned in mesh builder documentation.

**Comment by icefoxen** [comment]
That's a good idea.  Thank you!
