### ISSUE TITLE
Is the audio/gamepad switching on/off really necessary?

### ISSUE THREAD

**Issue by rhutsaliuk** [ggez/ggez#688]
Hi, folks.
I'm a rust newcomer from OOP world and want to make a small game on rust to better understand how it works. And gezz seems to be a perfect balance between complexity and features for me.
But I can see that uses null-patterns for audio and gamepad modules. I haven't really seen a game without sound support. Without controller, yes, definitely. 
But does it really make sense for `NullGamepadContext` & `NullAudioContext`? 
I could understand if that was some king of plug-in generics, but it just a `Box<dyn>` which does not leave a chance for compiler to optimize and throw away unused code. Whether or not user wants, he will get both modules in any case. So, why not just make them enabled default and if user does not want to play sounds or use gamepads, then he just does not do that?

I'm not complaining, but rather wandering what is the background for such decision.

**Comment by icefoxen** [comment]
Hi there!  Glad you like it.

I think these modules are enabled by default, so "don't use sounds or gamepads if you don't want to" is still a valid approach.  The main reason that the `Null*Context` types exist is due to interest in making ggez as a whole more modular, see #480 for details.  This would allow a bit more flexibility in platform support, since you can say "Well, `gilrs` doesn't support web yet, so there's no controller support for web, but `ggez` as a whole still builds and runs without any code changers".  It would also be nice for unit testing, since for instance you could set it up to still run *some* of the unit tests even if it's on, say, a VM with no audio output.

The end-goal really is for `GraphicsContext` to be swappable in the same way, but that's much larger and more complicated, and so gamepad and audio were done first as an experiment to pave the way.  The performance difference between a specialized generic and a `Box<dyn>` also seemed pretty inconsequential so we went with the latter since it let you swap between the different options without needing to recompile the program.

**Comment by rhutsaliuk** [comment]
Ok, that makes sense to me now. Thanks for explanations!
