### ISSUE TITLE
Give us access to the vfs module OR allow defining multiple file systems with fewer restrictions

### ISSUE THREAD

**Issue by alexschrod** [ggez/ggez#767]
I find the `filesystem` module to be very restricted, being limited to access a hard-coded `resources` mount point + a save location.

I'd like my game to have multiple locations where mods can be placed, and I'd like to load files on a per-mod basis. Essentially, I'm going to distribute a `core` mod with the game, and then I'd like every user-written mod to access files in
* their own mod folder/zip first
* then in the `core`

The `OverlayFS` struct and friends look perfect for this purpose, but alas, they're located inside the private `vfs` module.

**Comment by icefoxen** [comment]
Sorry for the long delay responding to this.  This is exactly the sort of usage that the `filesystem` module is *intended* to fulfill.  Is there some reason `ContextBuilder::add_resource_path()` doesn't work well enough for this?  Or `filesystem::mount()` if you desire.

This annoyingly gets a little squirrelly when it comes to locating config files, which is why it's not easier to add directories.  We need a config file to create a `Context`, but we need to know where to find the config file, and so it's a bit weird.  I'd like to make it better if you have suggestions, but not many people who use ggez seem interested in this use case.

**Comment by jpgadoury01** [comment]
Take a pointer to a function that specifies search directories?

**Comment by alexschrod** [comment]
I've reduced the scale of my project a bit since I wrote this, so the problem isn't really there anymore in my case, but the problem with using `add_resource_path` or `mount` is that it doesn't give enough control for what I wanted.

Essentially, I wanted mod file loading to act like this:
```
core
  |-mod a
  |-mod b
  |   \- mod b_2
  \-mod c
```

If "mod a" asked for a file it would only be looked for in "mod a" and in "core" but not in "mod b" or "mod c." Same for the others.

"mod b_2" however, would preferentially look in "mod b_2," then "mod b," and finally in "core."

The idea here was that mods could add its own stuff, while still being able to access everything in the core game or parent mods.

**Comment by icefoxen** [comment]
Seems like that sort of recursive mod loading would get complicated fast.  What if there was a `mod b_3` that overrode one of the same files that `mod b_2` did?  Which one would get used?

**Comment by icefoxen** [comment]
You *can* just not use the filesystem module at all and load everything yourself.  There's now functions to load all assets from raw data.
