### ISSUE TITLE
Parallel drawing with Rayon

### ISSUE THREAD

**Issue by laticoda** [ggez/ggez#784]
Hello, i  can't draw loop parallel with rayon because the ggez Context can't be sent between threads.
Is it possible to have a special mode to get it work, or an easy hack, i am newbie.

**Comment by mkhan45** [comment]
Hi @laticoda,

I guess you've come here from my repo. I probably should've elaborated more when I told you that the ggez context can't be passed between threads. Someone correct me if I'm wrong, but the ggez context contains the gpu info and whole lot of other low level stuff which is, right now, not feasible to pass between threads.

While you can make pretty much anything in your update loop parallel with rayon like you've done, you can't draw stuff in a parallel loop and there's no reasonable way to fix that.

**Comment by joetsoi** [comment]
I did some reading around on this before, from what I gather (and this is outside my area of expertise) is that its not possible it atm. I'd recommend reading

https://wiki.alopex.li/TheStateOfGGEZ2020
https://stackoverflow.com/questions/11097170/multithreaded-rendering-on-opengl
https://developer.nvidia.com/sites/default/files/akamai/gameworks/blog/munich/mschott_vulkan_multi_threading.pdf

It looks like ggez is looking towards targeting web assembly rather than vulkan. If you're a newbie, it's probably not worth worrying about multithreaded rendering for now if [YAGNI](https://en.wikipedia.org/wiki/You_aren%27t_gonna_need_it)

**Comment by icefoxen** [comment]
OpenGL itself is not multi-threaded, at least not well, so allowing parallel drawing with `ggez` would get minor gains at best.

**Comment by laticoda** [comment]
thank you everybody !
