### ISSUE TITLE
cgmath dependency in example 02

### ISSUE THREAD

**Issue by tlebrize** [ggez/ggez#797]
**Describe the bug**
the [example 02](https://github.com/ggez/ggez/blob/master/examples/02_hello_world.rs) needs the cgmath crate when it could simply use ggez's nalgebra.

**To Reproduce**
Run the copde without cgmath installed.

**Expected behavior**
Examples should be as painless as possible to run.

**Hardware and Software:**
 - ggez version: master

**Comment by tlebrize** [comment]
Being a rust and ggez beginner i don't know if theres a reason to use cgmath here, if not i'll remove it from all of the other examples.

**Comment by icefoxen** [comment]
The reason is basically to show off how to use `ggez` with different math libraries.  I want to gently discourage people from using `ggez::nalgebra` since `nalgebra` versions get changed a lot and it results in lots of complaints about `ggez` either updating to follow it, or not updating to follow it.

You're right though, the numbered examples should be as plug-and-play as possible.  Not sure what the best path forward here is.

**Comment by tlebrize** [comment]
Makes sense now, maybe bundle each example in a directory with it's own cargo.toml ?
