### ISSUE TITLE
EventHandler Error handling

### ISSUE THREAD

**Issue by OvermindDL1** [ggez/ggez#800]
The EventHandler hardcodes a GameError error type even though `event::run` does nothing more then return the error if it happens from the (very few, why not all?) callbacks on EventHandler.  The GameError trait, though useful for errors from the engine, are useless for user generated errors, and currently the user seems to not be able to delegate to a main error handler, but instead has to pepper error handling in every single one of their EventHandler callbacks.

It would be far more simple for users, and for more usual Rust, to just use the `std::error::Error` trait for error handling.  That way GameError can be passed in to it, as can any other user error type, then they can be uniformly handled in a single place when a fatal error has occurred.  This would significantly reduce the amount of needed error handling code used.

GameError already implements `std::error::Error` so it's already half-way there, just need to fix up the callbacks as well such as EventHandler.

This would significantly improve usability around error handling, and would fix one of the biggest nits that I keep encountering that forces me to write excess code.

**Comment by OvermindDL1** [comment]
As a secondary aside, the `GameError`'s implementation of `std::error::Error` is significantly lacking (most error details are just vanished, which is really really bad for debuggability...).  I would recommend using the `thiserror` library to simplify its implementation while ensuring that it is comprehensive and correct (plus it doesn't leak into the public API, it's just a derive).

**Comment by icefoxen** [comment]
I'd really like to do this, but it's surprisingly tricky to coalesce multiple error types together in a way that the `std::error::Error` trait likes.  I've tried to handle it a bit in the simple cases in commit cef04ec30572e649b67b2f5824f6c765f9be906b

**Comment by nobbele** [comment]
Can we just add `eprintln!("Error on EventHandler::update(): {:?}", e);` for update and draw beside the error! call?

**Comment by PSteinhaus** [comment]
I'm not sure I understand the issue here.
Is the idea that we want to return something more generic instead of GameResults, so that users can handle their own custom Errors together with any GameErrors that update or draw may throw? I haven't yet gotten into touch with Rusts error handling really, sry.

**Comment by nobbele** [comment]
Currently errors just fail silently unless you attach a logger

**Comment by nobbele** [comment]
Actually this issue might be unrelated lol

**Comment by PSteinhaus** [comment]
Now that error handling inside EventHandler has been improved the last thing to address is probably whether to use `thiserror` to rewrite most of the `GameError` implementation.

I've seen that @icefoxen already took a shot at improving this with f1df72273f6f205c459313535292b06a020f023b, which sadly had to be reversed. From your experience fiddling with this: Do you think it's worth trying out `thiserror`, or did you encounter anything forcing/incentivizing us to stay with the current implementation?

**Comment by icefoxen** [comment]
The problem with that commit was basically a clash with crates that try to losslessly wrap the underlying OS error (winit and maybe rodio, IIRC???), and which thus have sticky problems around doing things like cloning error structs or sending them through threads.  Now that I look at the problem again the simplest solution might be to make `GameError` not try to wrap `glutin::CreationError` or `gfx::shade::ProgramError` directly at all, but replace them with our own error types or stringify them.  It feels a little silly, but brute-force solutions to irritating problems is kinda what I'm about.  :sweat_smile: 

So, I think `thiserror` is orthogonal to that problem.  It looks fine, it just also looks to me like another step in the eternal "nice error handling library" cycle that I've seen go through like five steps since `ggez` started.

**Comment by PSteinhaus** [comment]
> Now that I look at the problem again the simplest solution might be to make GameError not try to wrap glutin::CreationError or gfx::shade::ProgramError directly at all, but replace them with our own error types or stringify them.

Hah, I think that's pretty much the opposite of what @OvermindDL1 had in mind (no pun intended).
It would be simpler, but if it already works, I don't see why we should do that. Wouldn't the main idea behind using `thiserror` be to use `#[from]` to simplify `from` implementations while also preserving more of the contained information at the same time, instead of crunching everything down into strings?

But then again, as I said, I'm basically a newbie when it comes to error handling in Rust, so I may simply hold a naive belief that `thiserror` can somehow magically derive implementations which avoid / correctly implement the sticky things, while it actually can't.

I haven't actually tried anything yet, but since you don't seem to oppose it, I guess I'll start a PR and t´start fiddling with this a little.

**Comment by nobbele** [comment]
thiserror doesn't avoid any weird stuff, it's just a convenience library AFAIK.

**Comment by nobbele** [comment]
Also, you could always wrap the underlying error types in Arcs and Mutexes to gain Clone-Send-Sync implementations

**Comment by PSteinhaus** [comment]
Ok, then it's probably not worth fiddling with `thiserror` right now.
Should we close this then, since the main issue has been resolved?

**Comment by OvermindDL1** [comment]
Yeah no point touching `thiserror`, it's nothing but a convenience library and I usually just end up doing what it does but manually, not like its hard, and its worth not having the compile cost the additional procmacro adds.

**Comment by PSteinhaus** [comment]
> The EventHandler hardcodes a GameError error type even though `event::run` does nothing more then return the error if it happens from the (very few, why not all?) callbacks on EventHandler.

I reopen this now to remind myself that I want to add results to all of the callbacks of EventHandler.
