### ISSUE TITLE
Updating to 0.3.0

### ISSUE THREAD

**Issue by Manghi** [ggez/ggez#89]
Hi,

I recently updated to `0.3.0` to try out some of the new shapes (circles, triangles, etc..). I was previously using ggez `0.2.1` and had made some decent progress in the project. After the update, I noticed a few things were different.

1. Pointers and Rectangles now accepted floats instead of unsigned integers
a. Rectangles could be created using `Rect::new_i32`, however this was not present for `Point`. I used `Point` all over so it'll be a bit of an effort to transition it to using `f32`. Was there any specific reason for changing from [unsigned] integers to floats?
2. Instantiating colors is a bit different, but no biggie since I'm happy as it supports alpha channels now (nice job!)
3. Getting the `height()` and `width()` of a rectangle is no longer supported 😞 

I must applaud you and the team on the improvements made under `0.3.0`, it's awesome. I can work past the usage of creating points and rectangles, but I cannot grasp my head around why getting the height and width of a rectangle isn't present anymore. These are the only ones I've caught so far. Am I missing something? 

Right now I'm thinking of branching off `0.3.0`and adding what I need in. Would you be willing to accept this some of this PR?

**Comment by icefoxen** [comment]
Glad 0.3.0 is getting stuff done for you, even if there's some bumps on the way.  Most of the changes are basically due to going from "how SDL2 thinks about the world" to "how gfx-rs thinks about the world".  GPU's generally use f32 for most/all things internally; SDL2's use of integer pixel coordinates and u8 colors is something of a convenient facade that then gets turned into f32 coordinates for the GPU anyway.  I dislike this facade; it simulates how graphics worked in 2002 or so before GPU's became ubiquitous and semi-standardized, but that's not how graphics systems work anymore and pretending they do doesn't gain you much.

The height and width of a rectangle are now exposed just via the `h` and `w` fields of it, as listed here: <https://docs.rs/ggez/0.3.0/ggez/graphics/struct.Rect.html> .  They needed to be methods in SDL-land because you were accessing C structures through FFI; now `Rect` and `Point` are just plain ol' Rust structs.

By all means, add whatever conversions for `Rect` and `Point` you want, I will be happy to accept a PR as long as it's useful and consistent.  I just haven't done it yet 'cause I don't know the best way to go about it.  I feel like the simplest way would be to implement `From` for various array types, so we could `impl From<[u32;4]> for Rect`, `impl From<[i32;4]> for Rect`, etc... but if you prefer having functions like `Rect::new_i32()` then we can add those instead.  It comes down to the same thing in the end, the question is just which is easier to use.

**Comment by Manghi** [comment]
Now that I understand a little bit more of what entailed during the transition to `0.3.x` I might forgo submitting a PR which would back-port some of the functionalities present in `0.2.x`. I thought at first the the community would benefit from this, but the shift in paradigm by you and the other devs was done for a very specific reason. 

If backwards compatibility was desired, it would have been at the heart of the transition. I only have seen it with respect to `Point` and `Rect` (among a few others) so far; I cannot comment on how involved it would be for all the other changes. Hopefully others will heed this call:

> What's changed? EVERYTHING.

Thank you for digging into the details a little bit regarding the shift from SDL2-centric to GFX. The shift, in my eyes at least, doesn't warrant adding in support for what was present under SDL2. That being said, will there be any effort to ensure backwards compatibility going forward? I think an effort of this nature would be better put as a moving forward statement than addressing the past ala _What's done is done_.

Feel free to close this issue once you get around to replying, if you can. Thanks @icefoxen & team.

**Comment by svenstaro** [comment]
I think at some point we'll slap 1.0 on this and from that point forwards there will be backwards compatibility. I don't think we should invest any resources in that before that point. It's going to bloat the code and frankly make it less fun to even reach 1.0

**Comment by icefoxen** [comment]
Yeah, we're sort of at the stage of "we think it looks like 1.0 but we can't prove it yet", I think.  Lots of functionality already exists and seems to work well, but lots of minor features could stand to be added and it's kinda hard to predict ahead of time how much they'll require changing the current API, or whether we can get away with just adding new stuff.
