### ISSUE TITLE
Cursor position is slightly off from actual position

### ISSUE THREAD

**Issue by junkmail22** [ggez/ggez#901]
A number of my playtesters are reporting an issue where the mouse position's in-game Y-coordinate is slightly above its actual position. This has occurred on more than one system, but does not occur on mine. It appears to happen most frequently on lower-end computers, although not universally.

Reproducing this bug is a nightmare, since I don't have access to a computer it occurs on, nor do I have precise specifications of the error.

If needed, I may be able to get a DxDiag from my playtesters.

**Comment by icefoxen** [comment]
This is a tricky one, I haven't seen anything like that... except for here: https://github.com/ggez/ggez/pull/884#issuecomment-774711643  But that's using release 0.6.  Still might be related though, it was an issue with hidpi support combined with a bug in how window sizes were determined, fixed here: https://github.com/ggez/ggez/pull/884/commits/53c3ac39dc90f31e8e38920fb5719653274de316#diff-d930d151a6f563eb078364d031f7de896835b8cec0fccccadb33e51c90ca87b2 .  So that would be the first place I look.

It sounds like the bug is reliably reproducable by your users at least, is that correct?  Do you have a binary or test case we can try to run?  I have access to a few different computers of varying specs for testing.

**Comment by junkmail22** [comment]
At the moment, I don't have a small test case since I haven't asked my testers to run one. I'll try sending a diagnostic program to my testers. I can absolutely send you a binary of the game itself, but it's currently in a place where testing for the mouse offset issue is kind of a pain in the ass.

**Comment by junkmail22** [comment]
We've managed to reproduce and narrow down the source of the issue: The issue only shows up when we changed the window size to be larger. In one reproduction, the window was larger than the screen of the computer. I'm not sure if this is something already known, now that the cause seems to be so banal.

I'll be working around this (guess I have to actually make different resolution options) but let me know what you plan to do with it.

**Comment by PSteinhaus** [comment]
@junkmail22 Are you sure that your bug is not caused by confusing ```graphics::size``` and ```graphics::drawable_size``` somewhere as in 53c3ac3[ #diff-d930d151a6f563eb078364d031f7de896835b8cec0fccccadb33e51c90ca87b2](https://github.com/ggez/ggez/commit/53c3ac39dc90f31e8e38920fb5719653274de316#diff-d930d151a6f563eb078364d031f7de896835b8cec0fccccadb33e51c90ca87b2)?
If not, have you checked whether this still occurs on 0.6? I ask just in case there aren't any breaking changes between 0.5.x and 0.6 preventing you from checking.

Also, are you calling [set_screen_coordinates](https://docs.rs/ggez/0.5.1/ggez/graphics/fn.set_screen_coordinates.html) after resizing to make sure logical and physical coordinate systems are identical? If not then any resizing will create differences between those two systems. On 0.5.x you also have to take the windows hidpi factor info account when calculating the actual window size from ```drawable_size``` by the way. This changes in 0.6, where hidpi factors are ignored, making the window actually be just as big as you specify in code.

**Comment by PSteinhaus** [comment]
@buxx Thanks for pointing that out.
This bug seems to be a different one though, since both x and y axis are affected. To be precise it's #883, which was fixed in #884.
I just checked and while I'm able to recreate the bug in 0.6.0-rc0 I cannot recreate it in the current devel branch anymore, so I'm confident it's fixed.

@junkmail22 I'd really like to know whether this bug still persists for you when using the devel branch. I know it doesn't build right now, but you can use #917. Again, this is only if it requires changing some boilerplate code on your side, so if there are no difficult breaking changes.
You say it happens when you change the window size to be larger. What do you mean by that? You mean changing the size programatically, not by resizing the window by hand, right? Such window size buggery _should_ be fixed now, but of course I can be wrong. If so, I'd really like to know, so that I can finally fix that for good.

**Comment by junkmail22** [comment]
@PSteinhaus Sorry, I should have said _initializing_ the window size as larger. If the window begins small, we don't get the error. If it begins large, it does get the error.

I've had weird mouse errors on 0.6 rc1, but I'm not currently in a buildable state for testing this at the moment. I'll get back to you as soon as I can test it on a new version.

**Comment by iiYese** [comment]
This issue is in the `0.6.0-rc0` and `0.6.0-rc1` as well. I lack the vocabulary to explain this better but it seems to me that the coordinate space of the rendering area is misaligned from the coordinate space of the window by some scale factor which is why resizing the window effects the perceived cursor position.

This scaling difference doesn't seem to be a constant either but rather depends on how much the window is off what size it should be. There is goldilocks zone where it behaves as it should.

[gif scaling behaviour](https://imgur.com/a/ywtvNcW)
[gif goldilocks](https://imgur.com/a/oThxfQo)

My main consists of this
```rust
use ggez::event;
use ggez::graphics::{self, Color};
use ggez::{Context, GameResult};
use glam::*;

struct MainState {
}

impl MainState {
    fn new() -> GameResult<MainState> {
        Ok(MainState {})
    }
}

impl event::EventHandler for MainState {
    fn update(&mut self, _ctx: &mut Context) -> GameResult {
        Ok(())
    }

    fn draw(&mut self, ctx: &mut Context) -> GameResult {
        graphics::clear(ctx, [0.1, 0.2, 0.3, 1.0].into());
        let pos = ggez::input::mouse::position(ctx);

        let circle = graphics::Mesh::new_circle(
            ctx,
            graphics::DrawMode::fill(),
            Vec2::new(pos.x, pos.y),
            5.0,
            2.0,
            Color::new(1.0, 1.0, 1.0, 1.0),
        )?;
        graphics::draw(ctx, &circle, (Vec2::new(0., 0.),))?;

        graphics::present(ctx)?;
        Ok(())
    }
}

pub fn main() -> GameResult {
    let cb = ggez::ContextBuilder::new("Bug", "iiYese");
    let (mut ctx, event_loop) = cb.build()?;
    let state = MainState::new()?;
    graphics::set_resizable(&mut ctx, true);
    event::run(ctx, event_loop, state)
}
```
With nothing else changed from the boiler plate examples other than setting the circle position to the mouse location and scaling. I tried setting the position with the `Vec2` in the `new_circle` and the `draw` calls but to no effect.

**Comment by iiYese** [comment]
I have this bug on 2 different systems. Both running Manjaro KDE Plasma. I'm running 0.6.0-rc1. It felt to me the coordinate spaces were off by some kind of scale factor and I wrote some code to test that out.

```rust
use ggez::{event, event::{KeyCode, KeyMods}, graphics::{Rect, drawable_size, set_screen_coordinates}};
use ggez::graphics::{self, Color};
use ggez::{Context, GameResult};
use glam::*;

struct MainState {
    correction: f32
}

impl MainState {
    fn new() -> GameResult<MainState> {
        Ok(MainState { correction: 1.0 })
    }
}

impl event::EventHandler for MainState {
    fn update(&mut self, ctx: &mut Context) -> GameResult {
        //need this here for when window resizes
        let (width, height) = drawable_size(ctx);
        set_screen_coordinates(ctx, Rect{ x: 0., y: 0., w: width * self.correction, h: height * self.correction });
        Ok(())
    }

    fn key_down_event(&mut self, ctx: &mut Context, keycode: KeyCode, _keymods: KeyMods, _repeat: bool) {
        self.correction += match keycode {
            KeyCode::Up => { 0.001 },
            KeyCode::Down => { -0.001 }
            _ => 0.
        };
        //need this here to get projection matrix change
        let (width, height) = drawable_size(ctx);
        set_screen_coordinates(ctx, Rect{ x: 0., y: 0., w: width * self.correction, h: height * self.correction });

        let p = graphics::projection(&ctx);
        println!("{:?}", p.x);
        println!("{:?}", p.y);
        println!("{:?}", p.z);
        println!("{:?}", p.w);
        println!("\ncorrection: {}\n", self.correction);
    }

    fn draw(&mut self, ctx: &mut Context) -> GameResult {
        graphics::clear(ctx, [0.1, 0.2, 0.3, 1.0].into());
        let pos = ggez::input::mouse::position(ctx);

        let circle = graphics::Mesh::new_circle(
            ctx,
            graphics::DrawMode::fill(),
            Vec2::new(pos.x, pos.y),
            5.0,
            2.0,
            Color::new(1.0, 1.0, 1.0, 1.0),
        )?;
        graphics::draw(ctx, &circle, (Vec2::new(0., 0.),))?;

        graphics::present(ctx)?;
        Ok(())
    }
}

pub fn main() -> GameResult {
    let cb = ggez::ContextBuilder::new("Rythm Engine", "iiYese")
        .window_mode(ggez::conf::WindowMode::default().dimensions(1920., 1080.));
    let (mut ctx, event_loop) = cb.build()?;
    let state = MainState::new()?;
    graphics::set_resizable(&mut ctx, true)?;
    let p = graphics::projection(&ctx);
    println!("{:?}", p.x);
    println!("{:?}", p.y);
    println!("{:?}", p.z);
    println!("{:?}", p.w);
    event::run(ctx, event_loop, state)
}
```

Arrow up and down keys control the correction factor and it's just printing the projection matrix and the scale factor itself to see what's going on. [This is what I got. A sort of botch fix?](https://user-images.githubusercontent.com/83026177/119184675-96d9f480-ba6d-11eb-860a-ae55f5385092.gif)

I think my observations are grasping at the issue? If I'm not wrong the only mutable thing I'm actually calling is the `set_screen_coordinates` function and looking at [the source code](https://docs.rs/ggez/0.6.0-rc1/src/ggez/graphics/mod.rs.html#626-631) 
```rust
pub fn set_screen_coordinates(context: &mut Context, rect: Rect) -> GameResult {
    let gfx = &mut context.gfx_context;
    gfx.set_projection_rect(rect);
    gfx.set_global_mvp(Matrix4::identity())
    //gfx.update_globals()
}
```
I think the bug or potential fix might be here? Could be an issue with the projection matrix algorithms? I can only make guesses my linear algebra hasn't caught up to that yet.

**Comment by nobbele** [comment]
Can't reproduce on windows 10 using that code

**Comment by PSteinhaus** [comment]
Can't reproduce it on my windows 10 either.
To me this seems very much like another one of these hidpi-issues I naively thought I finally ended once and for all by changing the window sizes to be measured in physical instead of logical pixels in #884. This fixed #883, as well as some other issues, so I'm a bit lost as to why this might not seem to be the case here.

Still, I might be wrong, so it would be great if you could try out 2 things:
- First, somewhere in your code, get your current window calling ```ggez::graphics::window``` and then call [```scale_factor```](https://docs.rs/winit/0.25.0/winit/window/struct.Window.html#method.scale_factor) on it to check whether this might actually be a hidpi issue.
- Then, if you can, please try to set the hidpi factor of your OS to 1 to check if that helps. I have no idea how this might work in Manjaro, but one thing you could try is setting the env variable ```WINIT_HIDPI_FACTOR=1``` (at least if that's still a thing in winit, haven't checked).

**Comment by iiYese** [comment]
Ok so I added this 
```rust
let sf = ggez::graphics::window(&ctx).scale_factor();
println!("Winit sf: {:?}\n", sf);
```
right above the `let p = graphics::projection(&ctx);` line in both the `main` and `key_down_event` functions. 

- This is what I get [before](https://user-images.githubusercontent.com/83026177/119230472-41a4ee00-bb14-11eb-9b6d-0c5891b64f5c.png) doing the correction with my code 
- This is what I get [after](https://user-images.githubusercontent.com/83026177/119230490-55505480-bb14-11eb-87fc-3bce6d3a5b4a.png)

So the scale factor winit is using isn't `1`. And the correction factor being that scale factor makes sense but isn't all that useful I guess?

I had a look around on Arch wiki and was unable to find anything on how to view or change the hidpi factor in the KDE section other than [this gui.](https://user-images.githubusercontent.com/83026177/119230551-921c4b80-bb14-11eb-9804-c7ba941a304f.png)
[This is what it's set to.](https://user-images.githubusercontent.com/83026177/119230615-f63f0f80-bb14-11eb-880b-1bd28d88b60c.png) I presume it adds to the multiplier since it's at 0%.

I also found this a bit further down
> Some programs may still interpret the DPI given by the X server

and checked my xserver settings. [Which yields nothing.](https://user-images.githubusercontent.com/83026177/119230921-3eaafd00-bb16-11eb-9f00-ee908bb958eb.png)

**Comment by PSteinhaus** [comment]
Aaand none of this (including setting ```WINIT_HIDPI_FACTOR=1```) changed anything?
Thanks for the hidpi factor. Now this really really looks like a hidpi issue, which is strange, since it probably means that winit creates a window with a logical size of (1920x1080) instead of a physical size of (1920x1080), as we ask of it...

**Comment by iiYese** [comment]
> Aaand none of this (including setting `WINIT_HIDPI_FACTOR=1`) changed anything?
> Thanks for the hidpi factor. Now this really really looks like a hidpi issue, which is strange, since it probably means that winit creates a window with a logical size of (1920x1080) instead of a physical size of (1920x1080), as we ask of it...
My settings in my system and xserver are already `+0` from the base of `1`. And the `WINIT_HIDPI_FACTOR` environment variable doesn't seem to exist on my system from my searching. I tried creating it by doing `export WINIT_HIDPI_FACTOR=1` with no effect.

**Comment by PSteinhaus** [comment]
Ok, I just realized I might have been a bit too quick.
As I said, there exists a potential fix for this issue in #884. The thing is, I thought this change already made it into 0.6.0-rc1, which, I just realized, isn't the case.

So before we try anything else, could you please check if using the current devel branch fixes your issue?

**Comment by PSteinhaus** [comment]
If that's true, then we really need to get a new release candidate out ASAP, since this would be the second time that this issue has popped up just in this thread alone in the last weeks, not counting all the previous issues we had with this.

**Comment by iiYese** [comment]
Just tested it there. The issue is not present in the `devel` branch.

**Comment by PSteinhaus** [comment]
Haha! Thank you! That's what I wanted to hear 😄 

Now I'd be really interested in knowing whether the mouse issues of @junkmail22 are still manifest when using the devel branch!
If even they would be gone I'd dare to hope again that we can finally stop messing around with this hidpi crap (that is, until we start working on a mobile port, where the whole thing may start anew 😢).

**Comment by IGBC** [comment]
> that is, until we start working on a mobile port,

does rust even work on android?

**Comment by nobbele** [comment]
yes

**Comment by icefoxen** [comment]
Yeah it does, getting the toolchain set up is just such a pain I never did it more than once.

**Comment by junkmail22** [comment]
Sorry for not responding sooner on this! I'm not super git-literate, so I haven't gotten around to using devel branch on my current build! I've been dealing with this bug recently, so hopefully this change works for me. The project is in a somewhat stable state right now, so I'll try updating to devel and seeing if it fixes things.

**Comment by junkmail22** [comment]
It sounds like the mouse issue has been fixed in devel! Thanks for helping with this.

**Comment by buxx** [comment]
Sorry :( , I reproduce the bug with the latest commit:

```
[package]
name = "playr"
version = "0.1.0"
authors = ["Sevajol Bastien <contact@bux.fr>"]
edition = "2018"

[dependencies]
ggez = { git = "https://github.com/ggez/ggez", rev = "359442b7869b580e8dae8435226e3888617ea5e8" }
glam = "0.12.0"
```

![116107370-43b19380-a6b3-11eb-8d6f-a4f6e9cb9b72](https://user-images.githubusercontent.com/1104637/123857906-30c17680-d923-11eb-9611-8eaea527874e.png)

Working reproducible code:

```
use ggez;
use ggez::graphics;
use ggez::graphics::{DrawMode, MeshBuilder, Color};
use ggez::{event};
use ggez::{Context, GameResult};
use glam::Vec2;

type Point2 = Vec2;

struct MainState {
    current_cursor_position: Point2,
}

impl MainState {
    fn new(_ctx: &mut Context) -> GameResult<MainState> {
        Ok(MainState {current_cursor_position: Point2::new(0.0, 0.0)})
    }
}

impl event::EventHandler for MainState {
    fn update(&mut self, _ctx: &mut Context) -> GameResult {
        Ok(())
    }

    fn draw(&mut self, ctx: &mut Context) -> GameResult {
        graphics::clear(ctx, Color::BLACK);

        let mut mesh_builder = MeshBuilder::new();
        mesh_builder.circle(
            DrawMode::fill(),
            self.current_cursor_position,
            10.0,
            2.0,
            Color::WHITE,
        )?;
        let mesh = mesh_builder.build(ctx)?;
        graphics::draw(
            ctx,
            &mesh,
            graphics::DrawParam::new()
                .dest(Point2::new(0.0, 0.0)),
        )?;

        graphics::present(ctx)?;

        Ok(())
    }

    fn mouse_motion_event(&mut self, _ctx: &mut Context, x: f32, y: f32, _dx: f32, _dy: f32) {
        self.current_cursor_position = Point2::new(x, y);
    }
}

pub fn main() -> GameResult {
    let cb = ggez::ContextBuilder::new("oc", "bux")
        .window_mode(ggez::conf::WindowMode::default().dimensions(800.0, 600.0));
    let (mut ctx, event_loop) = cb.build()?;
    let state = MainState::new(&mut ctx)?;
    event::run(ctx, event_loop, state)
}
```

**Comment by buxx** [comment]
I opened a new issue here : https://github.com/ggez/ggez/issues/956
