### ISSUE TITLE
More advanced font rendering

### ISSUE THREAD

**Issue by expenses** [ggez/ggez#92]
Hi, I've been having a great time with ggez so far, but I've found font rendering to be a little lacking.

Some features that would be appreciated:

* Setting the filtering mode of the font (nearest neighbor, linear interpolation etc.)
* Setting the colour of the font, and specifying a color in `Text::new`
* Changing the line height of the font

For some idea I'd also check out [love2d's font documentation](https://love2d.org/wiki/Font). Thanks a lot for a great library!

**Comment by icefoxen** [comment]
Filtering modes and colors are properties of the `Text`, not the font.  See <https://docs.rs/ggez/0.3.1/ggez/graphics/struct.Text.html#method.set_filter> for setting the filter mode, otherwise the one set by `graphics::set_default_filter()` will be used.  Text, like everything else, is drawn with the color set by `graphics::set_color()`, though one might argue that you should be able to set the color per `Text` object.  (Odd that love2d sets the filter mode on the font; I might have to look at that more.)

Cool shiny technicolor text rendering by specifying colors for particular strings should not be *super* hard to add to the engine but is not planned for the immediate future.  PR's welcome!  :D

Line height is a legit request

**Comment by icefoxen** [comment]
Fixed by #362!
