### ISSUE TITLE
Creating Image from TGA file fails

### ISSUE THREAD

**Issue by anpage** [ggez/ggez#973]
**Describe the bug**
Attempting to create a `ggez::graphics::Image` from a TGA file fails with
`ResourceLoadError("Image load error: The image format could not be determined")`

**To Reproduce**
```rust
ggez::graphics::Image::new(ctx, "/test.tga").unwrap();
```
panics:

```thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ResourceLoadError("Image load error: The image format could not be determined")'```

**Expected behavior**
A new Image should be created from the contents of the TGA file

**Screenshots or pasted code**
I'm rewriting an old game that used TGA files for some of its assets, so I can't convert them or I'd be abandoning a design goal of supporting the legacy resource files. I can invoke the `image` crate directly to work around the problem for now, but it would be nice if ggez directly supported the format. The feature flag is enabled in the library's dependencies, so I'm assuming support is intended.

Looking into the problem, `ggez::graphics::Image` uses the `image::load_from_memory()` function under the hood, which [the image crate docs](https://docs.rs/image/0.23.14/image/fn.load_from_memory.html) say doesn't support TGA. Maybe ggez can make a special case for `*.tga` files and use `image::load_from_memory_with_format()` or use `image::open()` instead for images loaded from the filesystem?

As an aside, it would be nice if the engine had the "jpeg" feature flag enabled for `image` as well, but I can see how it wouldn't have a strong use case in the vast majority of games.

**Hardware and Software:**
 - ggez version: 0.6.0
 - OS: Windows 10
 - Graphics card: Radeon RX 6900 XT
 - Graphics card drivers: 21.7.2

**Comment by trms-alex** [comment]
> I think you can override the feature selection to include jpeg for image, don't remember details though.

Yeah, that's what I'm doing. It's really not important as long as I'm able to do that, and maybe it'd be unnecessary bloat to enable it for everyone else's projects.

> Simple option would be to use a separate TGA file loader: https://crates.io/crates/tinytga for example.

`image` itself supports TGA fine. I can just use its `image::load_from_memory_with_format()` with `ggez::filesystem::open()` specifically for those files.

> Weird that TGA isn't supported by image::load_from_memory(), though.

I think `image::load_from_memory()` doesn't support it because TGA doesn't really have any kind of identifying signature, just a very short and simple header followed by a bitmap. `image` only tries to determine if some data is TGA based on the file extension, which it can't get from `image::load_from_memory()` alone.

**Comment by anpage** [comment]
> I think you can override the feature selection to include jpeg for image, don't remember details though.

Yeah, that's what I'm doing. It's really not important as long as I'm able to do that, and maybe it'd be unnecessary bloat to enable it for everyone else's projects.

> Simple option would be to use a separate TGA file loader: https://crates.io/crates/tinytga for example.

`image` itself supports TGA fine. I can just use its `image::load_from_memory_with_format()` with `ggez::filesystem::open()` specifically for those files.

> Weird that TGA isn't supported by image::load_from_memory(), though.

I think `image::load_from_memory()` doesn't support it because TGA doesn't really have any kind of identifying signature, just a very short and simple header followed by a bitmap. `image` only tries to determine if some data is TGA based on the file extension, which it can't get from `image::load_from_memory()` alone.

**Comment by PSteinhaus** [comment]
@anpage Thanks to your detailed description of your workaround it was really easy to add support for TGA.

I'd prefer to leave the "jpeg" feature disabled though, as ggez is also sometimes used by people new to programming games. And for them I'd like to keep it a touch more difficult to use jpeg than it is to use png, just because the latter is probably what you'd actually want to use in most cases.
And you also already discussed that it's really easy to enable it for yourself if you really need it.
