### ISSUE TITLE
Can't set the window position

### ISSUE THREAD

**Issue by gnevesdev** [ggez/ggez#974]
**How it happened**
I was trying to set the window position to center it on the screen, and found the `ggez::graphics::set_window_position` function. Though it takes a position argument that I can't supply, because it's from the `winit` crate, which is declared as private inside the graphics module of ggez.

More details here: https://docs.rs/ggez/0.6.0/ggez/graphics/fn.set_window_position.html

I found a way of getting around this, by getting the window position first, which would return me the struct from `winit`, so that I could modify it directly and use it as an argument for setting the new position.
```rs
let (ref mut ctx, event_loop) = &mut cb.build()?;
let window = graphics::window(ctx);
let mut pos = window.get_position().unwrap();
pos.x = 0.0;
pos.y = 0.0;
window.set_position(pos);
```
The problem with this is that it doesn't work anymore as of ggez 0.6.0, because there's no `get_position` anymore.

**Software details**
 - ggez version: 0.6.0
 - OS: Ubuntu

**Comment by PSteinhaus** [comment]
> it takes a position argument that I can't supply, because it's from the winit crate, which is declared as private inside the graphics module of ggez.

The winit crate is private inside the graphics module, but you could add it as a dependency on your own and then just do:
```rust
let (ctx, event_loop) = cb.build()?;
let pos = winit::dpi::PhysicalPosition::new(0.0,0.0);
graphics::set_window_position(&ctx, pos);
```
But since that might be unappealing there's luckily another option:

> I found a way of getting around this, by getting the window position first, which would return me the struct from winit, so that I could modify it directly and use it as an argument for setting the new position.

> The problem with this is that it doesn't work anymore as of ggez 0.6.0, because there's no `get_position` anymore.

There isn't but instead of it there are two new functions [`inner_position`](https://docs.rs/winit/0.24.0/winit/window/struct.Window.html#method.inner_position) and [`outer_position`](https://docs.rs/winit/0.24.0/winit/window/struct.Window.html#method.outer_position).
You probably want to use `outer_position`, as `set_window_position` calls `set_outer_position` under the hood.

I hope this helps you navigate your problem, but I guess the underlying issue is that we have `set_window_position`, but not `get_window_position`. I'm torn as to whether we want to add the latter. It would be easy enough, but honestly, I'd maybe even prefer to get rid of `set_window_position` instead, since we already expose the `Window` directly through `graphics::window` and all of these functions are basically just calling `graphics::window(ctx).some_function()`...

**Comment by PSteinhaus** [comment]
I took a look and it seems the feature arose from #807 leading to #839.
The short conversation shows that using the exposed `Window` to set its position directly has been perfectly possible without `set_window_position`. The only thing that might make it nice to have is that it seems to be used often enough to justify its existence as a simple convenience.

But if we say that it actually deserves to exist then we really need to add a `get_window_position` function as well, since `set_window_position` is pretty useless on its own, as it currently can only be used by also fiddling with the exposed `Window`, thereby eliminating the only reason for its own existence...

**Comment by PSteinhaus** [comment]
Added `get_window_position` in 3683d55.
